import type { Question } from './data'

const q = (
  id: string,
  topicId: string,
  prompt: string,
  options: string[],
  answer: number,
  explanationEs: string,
  vocabulary: Record<string, string> = {},
): Question => ({ id, topicId, prompt, options, answer, explanationEs, vocabulary })

export const expandedQuestionBank: Question[] = [
  q('xq1', 'parallel',
    'An agent must retrieve application logs, deployment metadata, and an independent service-status report before diagnosing an incident. What should it do FIRST?',
    ['Issue the three independent lookups in parallel, then synthesize.', 'Read each source sequentially to reduce context.', 'Diagnose before using tools.', 'Skip the status report.'], 0,
    'Las consultas son independientes y pueden ejecutarse en paralelo. La síntesis depende de recibir los tres resultados.',
    { retrieve: 'recuperar', independent: 'independiente' }),

  q('xq2', 'session-resumption',
    'A session resumes after two files changed while all prior findings were saved. Which approach is MOST efficient?',
    ['Restart the repository analysis from zero.', 'Reuse saved state and inspect only the changed files plus affected conclusions.', 'Trust every old conclusion without reading changes.', 'Discard the changed files.'], 1,
    'Se reutiliza el estado previo y se revisa únicamente lo modificado y sus conclusiones dependientes.',
    { resumes: 'reanuda', affected: 'afectado' }),

  q('xq3', 'subagent-prompts',
    'Which prompt BEST enables a subagent to compare two architecture proposals without requesting missing context?',
    ['Compare them and ask me later.', 'Read everything again.', 'Include the proposals, criteria, constraints, prior findings, sources, and required output.', 'Return anything relevant.'], 2,
    'Un prompt autocontenido incluye entradas, criterios, restricciones, hallazgos previos, fuentes y formato esperado.',
    { criteria: 'criterios', required: 'requerido' }),

  q('xq4', 'delegation',
    'A security investigation may change direction as evidence appears, but the coordinator needs visibility. Which delegation style is BEST?',
    ['No instructions.', 'A rigid procedure that cannot change.', 'A fixed file list only.', 'A goal-oriented assignment with success criteria, constraints, and checkpoints.'], 3,
    'La orientación a objetivos permite adaptación; los checkpoints mantienen control y visibilidad.',
    { evidence: 'evidencia', checkpoints: 'puntos de control' }),

  q('xq5', 'subagent-tools',
    'A subagent only needs to inspect configuration files and report risks. Which tool assignment follows least privilege?',
    ['Read-only discovery and inspection tools.', 'Repository-wide write and deployment access.', 'Database mutation tools.', 'Every coordinator tool.'], 0,
    'El agente solo necesita localizar y leer archivos. Los permisos mutantes amplían innecesariamente el riesgo.',
    { inspect: 'inspeccionar', privilege: 'privilegio' }),

  q('xq6', 'dynamic-decomposition',
    'During a migration analysis, an unexpected data-retention requirement appears. What should happen NEXT?',
    ['Ignore it because it was not in the original plan.', 'Add or revise a compliance subtask and update the plan.', 'Restart every completed task.', 'Mention it only after execution.'], 1,
    'La descomposición debe adaptarse a evidencia nueva sin repetir subtareas ya completadas.',
    { retention: 'retención', revise: 'revisar' }),

  q('xq7', 'review-architecture',
    'A production authorization change is high risk and requires human approval before execution. Which architecture is BEST?',
    ['Direct execution.', 'Parallel review and deployment.', 'Separate analysis, proposal, approval, and execution phases.', 'One unrestricted prompt.'], 2,
    'Los cambios sensibles requieren fases separadas y una aprobación explícita antes de ejecutar.',
    { approval: 'aprobación', execution: 'ejecución' }),

  q('xq8', 'state',
    'Which persisted checkpoint is MOST useful after a multi-hour workflow crashes?',
    ['Only the original request.', 'Only a timestamp.', 'Only the last prose response.', 'Completed tasks, pending tasks, outputs, references, errors, and retry counts.'], 3,
    'La reanudación confiable necesita saber qué terminó, qué falta, qué artefactos existen y qué errores ocurrieron.',
    { pending: 'pendiente', retry: 'reintento' }),

  q('xq9', 'cicd',
    'A CI job lets Claude Code propose fixes. Which control MOST directly reduces the blast radius of a mistake?',
    ['Restrict allowed tools and writable paths.', 'Increase temperature.', 'Remove timeouts.', 'Grant repository administration access.'], 0,
    'Los límites de herramientas y rutas modificables reducen directamente el alcance de una acción equivocada.',
    { 'blast radius': 'alcance del daño', writable: 'modificable' }),

  q('xq10', 'iterative',
    'A generated review misses three known defects. Which feedback is MOST likely to improve the next iteration?',
    ['Say do better.', 'Provide missed examples, violated criteria, and expected findings.', 'Change every parameter at once.', 'Request more words.'], 1,
    'El feedback específico permite corregir fallos concretos sin introducir cambios no diagnosticados.',
    { missed: 'omitido', violated: 'incumplido' }),

  q('xq11', 'review-config',
    'An automated reviewer sends findings to a ticketing system. Which output is MOST useful?',
    ['A long essay.', 'A boolean only.', 'Structured severity, file, line, evidence, and recommendation fields.', 'Opinions without locations.'], 2,
    'Los consumidores automáticos necesitan campos estables, trazables y validables.',
    { severity: 'severidad', evidence: 'evidencia' }),

  q('xq12', 'context-fork',
    'When is an isolated context fork MOST appropriate?',
    ['When every intermediate token must remain in the main session.', 'To replace project permissions.', 'To avoid defining an output.', 'For a lengthy specialist audit that should return only relevant findings.'], 3,
    'El contexto aislado evita llenar la sesión principal con detalles intermedios de una tarea especializada.',
    { lengthy: 'extenso', findings: 'hallazgos' }),

  q('xq13', 'test-generation',
    'Generated tests only assert that methods do not throw. What context should be added FIRST?',
    ['Expected behaviors, meaningful assertions, edge cases, fixtures, and existing conventions.', 'A higher test count.', 'Permission to delete failures.', 'The source file alone.'], 0,
    'Los comportamientos, fixtures y casos límite ayudan a crear pruebas útiles en lugar de aserciones triviales.',
    { fixtures: 'datos/preparación de prueba', 'edge cases': 'casos límite' }),

  q('xq14', 'configuration',
    'A repository needs general persistent guidance and a rule only for src/payments/**/*.java. Which setup is BEST?',
    ['Put everything in a temporary prompt.', 'Use CLAUDE.md for general guidance and .claude/rules/ with a path glob for the Java rule.', 'Use an MCP tool description.', 'Use shell aliases only.'], 1,
    'CLAUDE.md cubre instrucciones generales persistentes y .claude/rules/ permite reglas por ruta.',
    { persistent: 'persistente', glob: 'patrón de ruta' }),

  q('xq15', 'exploration',
    'You need to find where retry_limit appears inside YAML files. Which sequence is MOST appropriate?',
    ['Read the whole repository.', 'Use Bash to rewrite YAML.', 'Glob for YAML, Grep for retry_limit, then Read relevant matches.', 'Use Glob to search file contents.'], 2,
    'Glob localiza archivos, Grep busca contenido y Read inspecciona las coincidencias relevantes.',
    { relevant: 'relevante', matches: 'coincidencias' }),

  q('xq16', 'synthesis',
    'Two reliable sources report different totals and neither can be verified immediately. What should the synthesis do?',
    ['Average them silently.', 'Choose the larger value.', 'Remove the disagreement.', 'Preserve both values, attribute each source, and state uncertainty.'], 3,
    'La síntesis debe conservar desacuerdos e incertidumbre en lugar de inventar una única cifra.',
    { neither: 'ninguno', uncertainty: 'incertidumbre' }),

  q('xq17', 'human-review',
    'A system can send only a small fraction of outputs to people. Which case deserves the HIGHEST priority?',
    ['A low-confidence result from an unusual document with conflicting fields.', 'A common high-confidence result.', 'A short document only because it is short.', 'A random successful result.'], 0,
    'La baja confianza, el documento inusual y los campos contradictorios concentran el mayor riesgo.',
    { conflicting: 'contradictorio', priority: 'prioridad' }),

  q('xq18', 'batches',
    'A user is waiting for an immediate response to one request. Which option is LEAST appropriate?',
    ['A synchronous message request.', 'An asynchronous batch designed for deferred high-volume processing.', 'An interactive response.', 'Optimizing for low latency.'], 1,
    'Message Batches es adecuado para volumen diferido, no para una respuesta interactiva inmediata.',
    { deferred: 'diferido', immediate: 'inmediato' }),

  q('xq19', 'specialized-review',
    'A broad review prompt mixes security, logic, accessibility, style, and performance and misses issues. What is the BEST redesign?',
    ['Add more criteria to the same prompt.', 'Run the same prompt repeatedly.', 'Use specialized passes and synthesize their findings.', 'Remove project context.'], 2,
    'Separar preocupaciones permite prompts y ejemplos especializados; una síntesis posterior combina los resultados.',
    { broad: 'amplio', synthesize: 'sintetizar' }),

  q('xq20', 'structured',
    'A workflow must always produce data that validates against a required JSON schema. Which method is MOST reliable?',
    ['Ask for JSON in prose.', 'Parse an essay with regex.', 'Increase temperature.', 'Define a tool input schema and require the tool when structured output is mandatory.'], 3,
    'Tool use con JSON Schema y tool_choice ofrece mayor confiabilidad que solicitar JSON como texto libre.',
    { validates: 'valida', mandatory: 'obligatorio' }),

  q('xq21', 'schema',
    'One field may be absent, while another must exist but may explicitly contain null. How should they be modeled?',
    ['Make the first optional and the second nullable.', 'Invent defaults for both.', 'Use one unrestricted string.', 'Reject every missing value.'], 0,
    'Optional representa ausencia del campo; nullable permite que el valor explícito sea null.',
    { absent: 'ausente', nullable: 'admite null' }),

  q('xq22', 'truncation',
    'A structured audit of hundreds of files repeatedly stops before completing valid JSON. What should be tried FIRST?',
    ['Remove the schema.', 'Process smaller groups and merge independently valid results.', 'Request unlimited output.', 'Place more files in one prompt.'], 1,
    'Dividir la tarea reduce el tamaño de cada salida y permite una fusión determinista.',
    { repeatedly: 'repetidamente', merge: 'fusionar' }),

  q('xq23', 'extraction',
    'Invoices express dates and amounts in several formats. Which design BEST improves consistency?',
    ['A vague request.', 'One output string.', 'Representative examples, normalization rules, a schema, and explicit missing-field handling.', 'Invented defaults.'], 2,
    'Ejemplos y reglas de normalización mejoran consistencia; los campos ausentes deben representarse sin inventar.',
    { representative: 'representativo', normalization: 'normalización' }),

  q('xq24', 'boundaries',
    'A contract extractor returns promotional claims even though only obligations and termination clauses are needed. What is the BEST correction?',
    ['Ask for more findings.', 'Remove all examples.', 'Use a higher temperature.', 'Define explicit inclusion, exclusion, and boundary examples.'], 3,
    'Los límites de inclusión y exclusión reducen ruido y aclaran casos cercanos al borde.',
    { obligations: 'obligaciones', boundary: 'límite' }),

  q('xq25', 'builtin-tools',
    'You know the exact path of a small configuration file and need its contents. Which tool is MOST direct?',
    ['Read', 'Glob', 'Repository-wide Grep', 'A custom Bash crawler'], 0,
    'Read es la herramienta directa cuando la ruta ya es conocida.',
    { exact: 'exacta', contents: 'contenido' }),

  q('xq26', 'builtin-tools',
    'You need every occurrence of deprecated_endpoint inside source files. Which tool should be used?',
    ['Glob', 'Grep', 'Read one guessed file', 'A deployment tool'], 1,
    'Grep busca texto dentro de archivos; Glob busca nombres y rutas.',
    { occurrence: 'aparición', deprecated: 'obsoleto' }),

  q('xq27', 'tool-distribution',
    'A synthesis agent only combines findings produced by other agents. Which tool set is MOST appropriate?',
    ['Deployment and mutation tools.', 'Every worker tool.', 'Only tools needed to read outputs and produce the synthesis.', 'Unrestricted shell access.'], 2,
    'El agente debe recibir herramientas ajustadas a su rol; no necesita capacidades mutantes.',
    { combines: 'combina', synthesis: 'síntesis' }),

  q('xq28', 'mcp-resources',
    'An MCP server exposes a static catalog and an operation that submits an order. How should they be modeled?',
    ['Both as tools.', 'Catalog as a tool and submission as a resource.', 'Both as resources.', 'Catalog as a resource and submission as a tool.'], 3,
    'El catálogo es contenido de lectura; enviar una orden es una acción.',
    { static: 'estático', submits: 'envía' }),

  q('xq29', 'mcp-integration',
    'An MCP server is configured, but the client cannot discover its tools. What should be checked FIRST?',
    ['Scope, authentication, server configuration, and discovery.', 'Whether secrets can be committed.', 'Whether every resource is executable.', 'Whether descriptions use marketing language.'], 0,
    'La integración debe validar alcance, autenticación, configuración y discovery antes de asumir un fallo funcional.',
    { scope: 'alcance', discovery: 'descubrimiento' }),

  q('xq30', 'mcp-descriptions',
    'Tools named search_user and get_user are frequently confused. Which description improvement is BEST?',
    ['Give both the same generic description.', 'Explain use cases, inputs, outputs, limits, and how they differ.', 'Remove input descriptions.', 'Rename both user_tool.'], 1,
    'Las descripciones deben diferenciar claramente propósito, entradas, resultados y límites.',
    { differ: 'diferenciarse', limits: 'límites' }),

  q('xq31', 'tool-choice',
    'A transaction lookup needs an account ID returned by a customer-search tool. How should the calls run?',
    ['In parallel with an unknown ID.', 'By inventing an ID.', 'Customer search first, then transaction lookup with its result.', 'Transaction lookup first.'], 2,
    'La segunda llamada depende del resultado de la primera y debe ejecutarse en secuencia.',
    { lookup: 'consulta', depends: 'depende' }),

  q('xq32', 'tool-choice',
    'A compliance workflow must always call a validation tool before accepting extracted data. Which setting is MOST appropriate?',
    ['Leave validation optional.', 'Force an unrelated tool.', 'Replace validation with prose.', 'Use tool_choice to require the validation tool at that step.'], 3,
    'Cuando la invocación es obligatoria para continuar, tool_choice debe exigir la herramienta correcta.',
    { accepting: 'aceptando', require: 'exigir' }),
]
