import type { Question } from './data'

export const expandedQuestionBank: Question[] = [
  {
    id: 'xq1',
    topicId: 'parallel',
    prompt: 'An agent must check a deployment manifest, query an independent status API, and read an unrelated incident note before writing a summary. Which plan is MOST efficient?',
    options: [
      'Run the three independent operations in parallel and synthesize after all results arrive.',
      'Read the incident note first and postpone the other operations until the next turn.',
      'Generate the summary before gathering evidence.',
      'Run every operation sequentially because all tool calls must be serialized.',
    ],
    answer: 0,
    explanationEs: 'Las tres operaciones son independientes, por lo que pueden ejecutarse en paralelo. La síntesis sí debe esperar a que todos los resultados estén disponibles.',
    vocabulary: { unrelated: 'no relacionado', efficient: 'eficiente', arrive: 'llegar' },
  },
  {
    id: 'xq2',
    topicId: 'session-resumption',
    prompt: 'A coding session resumes after two files changed while the rest of the repository is unchanged. What should the agent do FIRST?',
    options: [
      'Discard all saved findings and restart the repository analysis.',
      'Reuse the saved state, inspect the changed files, and update only affected conclusions.',
      'Assume the previous conclusions are still correct without reading the changes.',
      'Read every file again before checking which files changed.',
    ],
    answer: 1,
    explanationEs: 'Al reanudar, se reutiliza el estado previo y se revisan los elementos modificados. Esto evita repetir trabajo sin ignorar cambios relevantes.',
    vocabulary: { resumes: 'reanuda', affected: 'afectado', unchanged: 'sin cambios' },
  },
  {
    id: 'xq3',
    topicId: 'subagent-prompts',
    prompt: 'A subagent must compare two architecture proposals and return a recommendation. Which prompt detail is LEAST appropriate to omit?',
    options: [
      'The required comparison criteria and success conditions.',
      'Decorative wording that does not affect the task.',
      'A greeting from the coordinator.',
      'The coordinator’s preferred writing style when no format is required.',
    ],
    answer: 0,
    explanationEs: 'Los criterios de comparación y las condiciones de éxito son esenciales para completar la tarea. Los elementos decorativos no aportan contexto operativo.',
    vocabulary: { least: 'menos', omit: 'omitir', criteria: 'criterios' },
  },
  {
    id: 'xq4',
    topicId: 'delegation',
    prompt: 'A security investigation may change direction as evidence appears, but the coordinator needs regular visibility. Which delegation style is BEST?',
    options: [
      'A goal-oriented assignment with constraints, success criteria, and checkpoints.',
      'A fixed procedure that forbids revising the investigation plan.',
      'An instruction containing only the word investigate.',
      'A request to return only after every possible lead has been exhausted.',
    ],
    answer: 0,
    explanationEs: 'La delegación orientada a objetivos permite adaptarse a nueva evidencia, mientras los checkpoints mantienen visibilidad y control.',
    vocabulary: { evidence: 'evidencia', checkpoints: 'puntos de control', forbids: 'prohíbe' },
  },
  {
    id: 'xq5',
    topicId: 'subagent-tools',
    prompt: 'A subagent only needs to inspect configuration files and report risks. Which tool assignment follows least privilege?',
    options: [
      'Read-only file discovery and inspection tools.',
      'Repository-wide write access and shell access.',
      'Deployment credentials plus database mutation tools.',
      'Every tool available to the coordinator.',
    ],
    answer: 0,
    explanationEs: 'El subagente solo necesita descubrir y leer archivos. Dar permisos de escritura o despliegue ampliaría innecesariamente el riesgo.',
    vocabulary: { inspect: 'inspeccionar', assignment: 'asignación', privilege: 'privilegio' },
  },
  {
    id: 'xq6',
    topicId: 'spawn-diagnostics',
    prompt: 'A configured subagent never starts after the coordinator requests it. What should be checked FIRST?',
    options: [
      'Whether the agent definition, invocation parameters, permissions, and coordinator wiring are valid.',
      'Whether increasing temperature makes the agent more willing to start.',
      'Whether the task can be rewritten with more adjectives.',
      'Whether all tools can be granted permanently.',
    ],
    answer: 0,
    explanationEs: 'Un fallo de inicio normalmente se diagnostica revisando definición, parámetros, permisos y conexión con el coordinador antes de ajustar generación.',
    vocabulary: { wiring: 'conexión', invocation: 'invocación', valid: 'válido' },
  },
  {
    id: 'xq7',
    topicId: 'dynamic-decomposition',
    prompt: 'During a migration analysis, an agent discovers an unexpected data-retention requirement. What is the MOST appropriate next step?',
    options: [
      'Create or revise a compliance subtask and update the plan.',
      'Ignore the requirement because it was not in the original decomposition.',
      'Restart every completed subtask.',
      'Continue the fixed plan and mention the requirement only in the final sentence.',
    ],
    answer: 0,
    explanationEs: 'La descomposición dinámica adapta el plan a evidencia nueva. Debe agregarse o modificarse una subtarea de cumplimiento sin repetir trabajo ya terminado.',
    vocabulary: { retention: 'retención', requirement: 'requisito', revise: 'revisar' },
  },
  {
    id: 'xq8',
    topicId: 'review-architecture',
    prompt: 'A developer requests a harmless formatting change in one documentation file. The change is easy to reverse and has no production impact. Which approach is MOST appropriate?',
    options: [
      'Direct execution with a quick validation.',
      'A four-phase workflow with two human approvals.',
      'A multi-agent security review before editing.',
      'A production change-management process.',
    ],
    answer: 0,
    explanationEs: 'Una tarea simple, reversible y de bajo riesgo no necesita una arquitectura multifase. La ejecución directa con validación es proporcional al riesgo.',
    vocabulary: { harmless: 'inofensivo', reverse: 'revertir', impact: 'impacto' },
  },
  {
    id: 'xq9',
    topicId: 'state',
    prompt: 'Which checkpoint is MOST useful for resuming a multi-step document pipeline after a crash?',
    options: [
      'Completed item IDs, pending items, produced artifacts, errors, and retry counts.',
      'Only the original user prompt.',
      'Only the last model response as unstructured prose.',
      'A timestamp without task state.',
    ],
    answer: 0,
    explanationEs: 'Un checkpoint útil debe indicar qué terminó, qué falta, qué artefactos existen y qué errores o reintentos ocurrieron.',
    vocabulary: { crash: 'caída', produced: 'producido', retry: 'reintento' },
  },
  {
    id: 'xq10',
    topicId: 'orchestration',
    prompt: 'Four agents independently inspect security, performance, reliability, and maintainability. A final agent combines their findings. Which pattern is being used?',
    options: [
      'Parallel specialist workers followed by synthesis.',
      'A strictly sequential dependency chain.',
      'Direct execution without delegation.',
      'A single procedural subagent with no coordinator.',
    ],
    answer: 0,
    explanationEs: 'Los revisores especializados trabajan en paralelo porque sus tareas son independientes y luego un agente sintetiza los resultados.',
    vocabulary: { combines: 'combina', findings: 'hallazgos', followed: 'seguido' },
  },
  {
    id: 'xq11',
    topicId: 'cicd',
    prompt: 'A CI job lets Claude Code propose a patch. Which control MOST directly reduces the blast radius of a mistaken action?',
    options: [
      'Restrict writable paths and allowed tools for the job.',
      'Increase the context window.',
      'Remove the timeout so the job can self-correct.',
      'Grant repository administration access.',
    ],
    answer: 0,
    explanationEs: 'Limitar rutas modificables y herramientas reduce directamente el alcance de una acción equivocada. El contexto no reemplaza controles de permisos.',
    vocabulary: { blast radius: 'alcance del daño', writable: 'modificable', mistaken: 'equivocado' },
  },
  {
    id: 'xq12',
    topicId: 'iterative',
    prompt: 'A generated review misses three known defects. Which feedback is MOST likely to improve the next iteration?',
    options: [
      'Provide the missed examples, violated criteria, and expected findings.',
      'Say be more careful without examples.',
      'Increase temperature and change every instruction at once.',
      'Ask for a longer answer regardless of content.',
    ],
    answer: 0,
    explanationEs: 'El feedback específico muestra qué se omitió, qué criterio se incumplió y qué salida se esperaba. Esto permite una mejora dirigida.',
    vocabulary: { misses: 'omite', violated: 'incumplido', iteration: 'iteración' },
  },
  {
    id: 'xq13',
    topicId: 'review-config',
    prompt: 'An automated code reviewer feeds findings into a ticketing system. Which output design is BEST?',
    options: [
      'A structured schema containing severity, file, line, evidence, and recommendation.',
      'Unstructured prose with no stable fields.',
      'A single boolean indicating whether the code is perfect.',
      'A list of opinions without source locations.',
    ],
    answer: 0,
    explanationEs: 'Un consumidor automático necesita campos estables y trazables como severidad, ubicación, evidencia y recomendación.',
    vocabulary: { feeds: 'entrega/alimenta', severity: 'severidad', evidence: 'evidencia' },
  },
  {
    id: 'xq14',
    topicId: 'context-fork',
    prompt: 'When is an isolated context fork MOST useful?',
    options: [
      'For a lengthy specialist audit whose intermediate details should not fill the main session.',
      'When every intermediate token must remain in the main context.',
      'For replacing persistent project instructions.',
      'For granting additional filesystem permissions.',
    ],
    answer: 0,
    explanationEs: 'Un contexto aislado es útil para trabajo especializado extenso que solo debe devolver hallazgos relevantes a la sesión principal.',
    vocabulary: { lengthy: 'extenso', audit: 'auditoría', fill: 'llenar' },
  },
  {
    id: 'xq15',
    topicId: 'test-generation',
    prompt: 'A test generator creates many tests that only assert that methods do not throw. What should the team add FIRST?',
    options: [
      'Expected behaviors, meaningful assertions, boundary cases, and existing test conventions.',
      'A higher requested test count.',
      'Permission to delete failing tests.',
      'A requirement that every test use the same input.',
    ],
    answer: 0,
    explanationEs: 'Los comportamientos esperados, aserciones significativas y casos límite evitan pruebas triviales que no validan la lógica real.',
    vocabulary: { assert: 'comprobar', boundary: 'límite', meaningful: 'significativo' },
  },
  {
    id: 'xq16',
    topicId: 'configuration',
    prompt: 'A repository needs permanent general guidance plus a rule that applies only to migration scripts. Which configuration is BEST?',
    options: [
      'Place general guidance in CLAUDE.md and the path-specific rule in .claude/rules/ with a matching glob.',
      'Put both rules in a temporary chat message.',
      'Store both rules in an unrelated tool description.',
      'Use shell aliases as the only project instructions.',
    ],
    answer: 0,
    explanationEs: 'CLAUDE.md sirve para guía persistente general y .claude/rules/ permite reglas condicionadas por rutas o globs.',
    vocabulary: { permanent: 'permanente', matching: 'coincidente', guidance: 'guía' },
  },
  {
    id: 'xq17',
    topicId: 'exploration',
    prompt: 'You need to find where a configuration key named retry_limit appears in YAML files. Which sequence is MOST appropriate?',
    options: [
      'Glob for YAML files, Grep for retry_limit, then Read the relevant matches.',
      'Read the entire repository before searching.',
      'Use Bash to rewrite every YAML file.',
      'Use Glob to search inside file contents only.',
    ],
    answer: 0,
    explanationEs: 'Glob localiza archivos, Grep busca contenido y Read inspecciona los resultados relevantes. Es una exploración incremental.',
    vocabulary: { appears: 'aparece', relevant: 'relevante', matches: 'coincidencias' },
  },
  {
    id: 'xq18',
    topicId: 'output-schema',
    prompt: 'A coordinator must merge findings from several subagents automatically. Which subagent response is MOST useful?',
    options: [
      'A stable structured list of findings with source references and confidence metadata.',
      'A creative essay with no identifiers.',
      'A one-word answer.',
      'Raw chain-of-thought without a result schema.',
    ],
    answer: 0,
    explanationEs: 'La síntesis automática requiere estructura estable, referencias y metadatos. La prosa libre dificulta combinar y validar resultados.',
    vocabulary: { merge: 'fusionar', stable: 'estable', confidence: 'confianza' },
  },
  {
    id: 'xq19',
    topicId: 'synthesis',
    prompt: 'Two sources report different transaction totals and neither can be verified immediately. What should the synthesis do?',
    options: [
      'Preserve both values, identify their sources, and state the uncertainty.',
      'Average the totals and present the result as certain.',
      'Choose the larger value without explanation.',
      'Remove the disagreement from the report.',
    ],
    answer: 0,
    explanationEs: 'La síntesis confiable no debe ocultar conflictos. Debe atribuir cada cifra y expresar la incertidumbre hasta resolverla.',
    vocabulary: { neither: 'ninguno', preserve: 'conservar', uncertainty: 'incertidumbre' },
  },
  {
    id: 'xq20',
    topicId: 'long-context',
    prompt: 'A long coding session contains thousands of exploratory details but only a few decisions remain relevant. What is the BEST context strategy?',
    options: [
      'Persist a compact scratchpad of decisions and reload only relevant evidence.',
      'Repeat the full transcript before every action.',
      'Delete all previous decisions and start over.',
      'Keep every tool result in the active prompt indefinitely.',
    ],
    answer: 0,
    explanationEs: 'Un scratchpad compacto conserva decisiones, pendientes y evidencia necesaria sin mantener detalles exploratorios irrelevantes en el contexto activo.',
    vocabulary: { exploratory: 'exploratorio', remain: 'permanecer', indefinitely: 'indefinidamente' },
  },
  {
    id: 'xq21',
    topicId: 'human-review',
    prompt: 'An extraction system can send only a small fraction of cases to people. Which case should receive the HIGHEST review priority?',
    options: [
      'A low-confidence result from an unusual document with conflicting fields.',
      'A high-confidence result matching common examples.',
      'A short document solely because it is short.',
      'A random successful result with no risk indicators.',
    ],
    answer: 0,
    explanationEs: 'La baja confianza, el documento fuera de distribución y los campos contradictorios concentran riesgo y justifican revisión humana.',
    vocabulary: { fraction: 'fracción', conflicting: 'contradictorio', priority: 'prioridad' },
  },
  {
    id: 'xq22',
    topicId: 'batches',
    prompt: 'A user is waiting for an immediate answer to one support request. Which choice is LEAST appropriate?',
    options: [
      'Submitting the request to an asynchronous batch intended for deferred high-volume work.',
      'Using a synchronous message request.',
      'Returning the result directly when processing completes.',
      'Optimizing for interactive latency.',
    ],
    answer: 0,
    explanationEs: 'Message Batches es para volumen asíncrono y diferido, no para una interacción donde el usuario espera una respuesta inmediata.',
    vocabulary: { deferred: 'diferido', immediate: 'inmediato', least: 'menos' },
  },
  {
    id: 'xq23',
    topicId: 'specialized-review',
    prompt: 'A single review prompt mixes security, logic, accessibility, style, and performance and misses issues in every category. What is the BEST redesign?',
    options: [
      'Use specialized passes for separate concerns, then synthesize their findings.',
      'Add more unrelated criteria to the same prompt.',
      'Remove all examples and project context.',
      'Run the same broad prompt repeatedly without changing it.',
    ],
    answer: 0,
    explanationEs: 'Separar preocupaciones reduce la competencia entre criterios y permite prompts, ejemplos y herramientas especializados antes de sintetizar.',
    vocabulary: { concern: 'preocupación', broad: 'amplio', synthesize: 'sintetizar' },
  },
  {
    id: 'xq24',
    topicId: 'structured',
    prompt: 'A payment workflow must always emit fields that validate against a required schema. Which implementation is MOST reliable?',
    options: [
      'Define a tool input schema and require the tool call when structured output is mandatory.',
      'Ask for valid JSON in prose and trust the model completely.',
      'Extract fields later with regular expressions from an essay.',
      'Use a higher temperature to increase schema variety.',
    ],
    answer: 0,
    explanationEs: 'Cuando la estructura es obligatoria, una herramienta con JSON Schema y tool_choice ofrece una salida más verificable que instrucciones de texto.',
    vocabulary: { emit: 'emitir', mandatory: 'obligatorio', validate: 'validar' },
  },
  {
    id: 'xq25',
    topicId: 'schema',
    prompt: 'A field may legitimately be absent, while another field must exist but may explicitly contain null. How should these be modeled?',
    options: [
      'Make the first optional and allow null for the second.',
      'Require both as non-null strings and invent values when missing.',
      'Remove both fields from the schema.',
      'Represent the complete object as one free-form string.',
    ],
    answer: 0,
    explanationEs: 'Optional representa que el campo puede omitirse. Nullable representa que el campo existe y null es un valor permitido.',
    vocabulary: { legitimately: 'legítimamente', absent: 'ausente', explicitly: 'explícitamente' },
  },
  {
    id: 'xq26',
    topicId: 'tool-schema',
    prompt: 'A tool accepts an account ID and an optional date range. Which schema design is BEST?',
    options: [
      'Require a typed account ID, define typed optional dates, and describe valid formats and constraints.',
      'Accept one unrestricted string named data.',
      'Mark every field optional even when the tool cannot work without an account ID.',
      'Omit descriptions because field names are always sufficient.',
    ],
    answer: 0,
    explanationEs: 'El esquema debe reflejar requisitos reales, tipos, formatos y restricciones. Un input genérico reduce validación y claridad para el modelo.',
    vocabulary: { range: 'rango', constraints: 'restricciones', sufficient: 'suficiente' },
  },
  {
    id: 'xq27',
    topicId: 'truncation',
    prompt: 'A structured audit of 400 files repeatedly stops before completing the JSON object. Which change should be tried FIRST?',
    options: [
      'Process smaller file groups and merge independently valid results.',
      'Remove all structure requirements.',
      'Request an unlimited output length.',
      'Place all files into one larger prompt.',
    ],
    answer: 0,
    explanationEs: 'Dividir el trabajo reduce el tamaño de cada salida y permite fusionar resultados válidos de forma determinista.',
    vocabulary: { repeatedly: 'repetidamente', independently: 'independientemente', merge: 'fusionar' },
  },
  {
    id: 'xq28',
    topicId: 'extraction',
    prompt: 'Invoices express dates and amounts in several formats. Which prompt design BEST improves consistent extraction?',
    options: [
      'Provide representative examples, normalization rules, a schema, and explicit handling for missing fields.',
      'Use a vague request and high temperature.',
      'Store the entire invoice in one output string.',
      'Invent defaults whenever a field is absent.',
    ],
    answer: 0,
    explanationEs: 'Los ejemplos, reglas de normalización, esquema y tratamiento de ausencias permiten resultados consistentes sin inventar datos.',
    vocabulary: { invoices: 'facturas', representative: 'representativo', handling: 'tratamiento' },
  },
  {
    id: 'xq29',
    topicId: 'false-positives',
    prompt: 'A reviewer flags an architectural pattern that the project explicitly permits. What is the MOST effective fix?',
    options: [
      'Add the accepted pattern and exclusion criteria to persistent project guidance.',
      'Ask the reviewer to produce more findings.',
      'Increase temperature.',
      'Remove all project-specific context.',
    ],
    answer: 0,
    explanationEs: 'Documentar patrones aceptados y exclusiones reduce falsos positivos al alinear la revisión con las reglas reales del proyecto.',
    vocabulary: { flags: 'marca', permits: 'permite', exclusion: 'exclusión' },
  },
  {
    id: 'xq30',
    topicId: 'boundaries',
    prompt: 'A contract extractor returns marketing claims even though only obligations and termination clauses are needed. Which instruction is MOST useful?',
    options: [
      'Define explicit inclusion categories, exclusion categories, and boundary examples.',
      'Ask for anything interesting.',
      'Request more output without changing the scope.',
      'Remove examples to avoid influencing the model.',
    ],
    answer: 0,
    explanationEs: 'Los límites explícitos de inclusión y exclusión reducen ruido y ayudan a resolver casos cercanos al borde.',
    vocabulary: { obligations: 'obligaciones', clauses: 'cláusulas', boundary: 'límite' },
  },
  {
    id: 'xq31',
    topicId: 'context-optimization',
    prompt: 'Which information should be retained when compacting an agent conversation?',
    options: [
      'Current goals, decisions, unresolved questions, constraints, and references needed for pending work.',
      'Every repeated greeting and discarded hypothesis.',
      'Only the first user message.',
      'Nothing from previous turns.',
    ],
    answer: 0,
    explanationEs: 'La compactación debe preservar estado operativo: objetivos, decisiones, restricciones, pendientes y referencias necesarias.',
    vocabulary: { retained: 'conservado', compacting: 'compactando', unresolved: 'no resuelto' },
  },
  {
    id: 'xq32',
    topicId: 'tool-choice',
    prompt: 'A transaction lookup requires an account ID returned by a customer-search tool. How should the calls be scheduled?',
    options: [
      'Call customer search first, then use its account ID in the transaction lookup.',
      'Call both in parallel with an unknown account ID.',
      'Force the transaction tool before obtaining its required input.',
      'Skip customer search and invent an account ID.',
    ],
    answer: 0,
    explanationEs: 'Existe una dependencia de datos: la segunda herramienta necesita el resultado de la primera, por lo que deben ejecutarse en secuencia.',
    vocabulary: { requires: 'requiere', scheduled: 'programadas', obtaining: 'obteniendo' },
  },
  {
    id: 'xq33',
    topicId: 'builtin-tools',
    prompt: 'You already know the exact path of a small configuration file and need to inspect its contents. Which tool is MOST direct?',
    options: [
      'Read',
      'Glob',
      'Grep across the entire repository',
      'Bash with a custom filesystem crawler',
    ],
    answer: 0,
    explanationEs: 'Cuando la ruta ya es conocida y se necesita el contenido, Read es la herramienta directa. Glob y Grep resuelven búsquedas distintas.',
    vocabulary: { exact: 'exacta', inspect: 'inspeccionar', direct: 'directa' },
  },
  {
    id: 'xq34',
    topicId: 'builtin-tools',
    prompt: 'You need to find every occurrence of the text deprecated_endpoint inside source files. Which built-in tool should be used?',
    options: [
      'Grep',
      'Glob',
      'Read one guessed file',
      'A deployment tool',
    ],
    answer: 0,
    explanationEs: 'Grep busca apariciones de texto dentro de archivos. Glob se utiliza para patrones de nombres o rutas.',
    vocabulary: { occurrence: 'aparición', deprecated: 'obsoleto', source: 'código fuente' },
  },
  {
    id: 'xq35',
    topicId: 'tool-distribution',
    prompt: 'A synthesis agent only combines findings already produced by workers. Which tool set is MOST appropriate?',
    options: [
      'Only the tools needed to read worker outputs and produce the synthesis.',
      'Production deployment and database mutation tools.',
      'Every tool held by every worker.',
      'Unrestricted shell access by default.',
    ],
    answer: 0,
    explanationEs: 'El agente de síntesis debe recibir solo lo necesario para leer resultados y combinarlos. Herramientas mutantes no corresponden a su rol.',
    vocabulary: { combines: 'combina', held: 'poseído', unrestricted: 'sin restricciones' },
  },
  {
    id: 'xq36',
    topicId: 'mcp-resources',
    prompt: 'An MCP server exposes a static product catalog and an operation that submits an order. How should they be modeled?',
    options: [
      'Catalog as a resource; order submission as a tool.',
      'Both as destructive tools.',
      'Catalog as a mutation tool; order submission as a resource.',
      'Both as plain prompt text with no interface.',
    ],
    answer: 0,
    explanationEs: 'El catálogo es contenido para lectura y corresponde a un resource. Enviar una orden ejecuta una acción y corresponde a una tool.',
    vocabulary: { static: 'estático', submits: 'envía', modeled: 'modelados' },
  },
  {
    id: 'xq37',
    topicId: 'mcp-integration',
    prompt: 'An MCP server is configured, but the client cannot see any of its tools. What should be verified FIRST?',
    options: [
      'Scope, authentication, server configuration, and tool discovery.',
      'Whether all credentials can be hard-coded into the repository.',
      'Whether the tool descriptions contain marketing language.',
      'Whether every resource can be converted into a mutation.',
    ],
    answer: 0,
    explanationEs: 'Cuando las herramientas no aparecen, se revisan alcance, autenticación, configuración y discovery antes de modificar el diseño funcional.',
    vocabulary: { configured: 'configurado', discovery: 'descubrimiento', verified: 'verificado' },
  },
  {
    id: 'xq38',
    topicId: 'mcp-descriptions',
    prompt: 'Two MCP tools named search_user and get_user are frequently confused. Which description improvement is BEST?',
    options: [
      'Explain when to use each tool, required inputs, returned data, limits, and how they differ.',
      'Rename both tools to user_tool.',
      'Remove input descriptions.',
      'Describe both as useful for users without further detail.',
    ],
    answer: 0,
    explanationEs: 'Las descripciones deben diferenciar propósito, inputs, salida y límites para que el modelo seleccione la herramienta correcta.',
    vocabulary: { confused: 'confundidas', differ: 'diferenciarse', limits: 'límites' },
  },
  {
    id: 'xq39',
    topicId: 'tool-choice',
    prompt: 'A compliance workflow must always call a validation tool before accepting extracted data. Which setting is MOST appropriate?',
    options: [
      'Use tool_choice to require the validation tool at that step.',
      'Leave validation entirely optional even though acceptance depends on it.',
      'Force an unrelated search tool.',
      'Replace validation with free-form prose.',
    ],
    answer: 0,
    explanationEs: 'Cuando una llamada es obligatoria para continuar, tool_choice permite exigirla. No debe forzarse una herramienta que no corresponde.',
    vocabulary: { accepting: 'aceptando', require: 'exigir', unrelated: 'no relacionada' },
  },
  {
    id: 'xq40',
    topicId: 'mcp-integration',
    prompt: 'Which credential practice is LEAST appropriate for an MCP integration?',
    options: [
      'Committing long-lived secrets directly into the repository configuration.',
      'Supplying credentials through an approved secret-management mechanism.',
      'Limiting credentials to the required scope.',
      'Verifying authentication before tool discovery tests.',
    ],
    answer: 0,
    explanationEs: 'Los secretos no deben quedar hardcodeados ni versionados. Se deben usar mecanismos aprobados y permisos con alcance mínimo.',
    vocabulary: { credential: 'credencial', long-lived: 'de larga duración', committing: 'versionando' },
  },
]
