import type { Question } from './data'

export const extraExamQuestions: Question[] = [
  {
    id: 'q16',
    topicId: 'parallel',
    prompt: 'An incident-response agent must retrieve application logs, infrastructure metrics, and deployment metadata before producing a diagnosis. None of the three lookups depends on another. What should the agent do FIRST?',
    options: [
      'Retrieve each source sequentially so the model has less context at once.',
      'Issue the three lookups in parallel, then synthesize the results.',
      'Produce a preliminary diagnosis before calling any tools.',
      'Delegate all three lookups to the same tool call even if the tool does not support it.',
    ],
    answer: 1,
    explanationEs: 'Como las tres consultas son independientes, ejecutarlas en paralelo reduce la latencia total. La síntesis debe ocurrir después de recibir todos los resultados.',
    vocabulary: { retrieve: 'recuperar', depends: 'depende', first: 'primero' },
  },
  {
    id: 'q17',
    topicId: 'subagent-prompts',
    prompt: 'A coordinator delegates a final compliance summary after two agents have already extracted findings and source references. Which subagent prompt is MOST complete?',
    options: [
      'Summarize the compliance issue. Ask for more context if needed.',
      'Review the original documents again and ignore previous findings.',
      'Use the attached findings, source references, unresolved conflicts, constraints, and required output schema to produce the final summary.',
      'Return any observations that appear relevant.',
    ],
    answer: 2,
    explanationEs: 'El subagente debe recibir los hallazgos previos, las fuentes, los conflictos pendientes, las restricciones y el formato esperado. Así puede terminar sin pedir contexto faltante ni repetir trabajo.',
    vocabulary: { attached: 'adjunto', unresolved: 'no resuelto', required: 'requerido' },
  },
  {
    id: 'q18',
    topicId: 'review-architecture',
    prompt: 'A team is changing production authorization rules. The change is high risk, requires security review, and must not be applied until a human approves the proposed modifications. Which architecture is BEST?',
    options: [
      'Direct execution with unrestricted write access.',
      'A single prompt that reviews and immediately applies every change.',
      'A multi-phase workflow that separates analysis, proposed changes, human approval, and execution.',
      'A parallel workflow where review and deployment happen at the same time.',
    ],
    answer: 2,
    explanationEs: 'Un cambio sensible de autorización debe separar análisis, propuesta, aprobación humana y ejecución. La arquitectura multifase reduce riesgo y mantiene trazabilidad.',
    vocabulary: { until: 'hasta que', proposed: 'propuesto', applies: 'aplica' },
  },
  {
    id: 'q19',
    topicId: 'state',
    prompt: 'A multi-agent migration workflow can be interrupted after several hours. Which persisted state is LEAST sufficient for a reliable resume?',
    options: [
      'The original user request only.',
      'Completed task IDs, pending tasks, outputs, and checkpoint timestamps.',
      'Completed steps, errors, retry counts, and source references.',
      'The latest checkpoint plus the artifacts required by unfinished tasks.',
    ],
    answer: 0,
    explanationEs: 'Guardar solo la solicitud original no permite saber qué tareas terminaron, cuáles siguen pendientes ni qué resultados ya existen. La reanudación confiable requiere estado estructurado y checkpoints.',
    vocabulary: { least: 'menos', sufficient: 'suficiente', unfinished: 'sin terminar' },
  },
  {
    id: 'q20',
    topicId: 'cicd',
    prompt: 'A pull-request pipeline uses Claude Code to inspect changes and suggest fixes. Which configuration BEST limits runaway automation?',
    options: [
      'Interactive mode with unlimited turns and repository-wide write access.',
      'Non-interactive execution with turn, cost, timeout, and file-permission limits.',
      'Automatic retries until the model produces no findings.',
      'A larger context window without execution limits.',
    ],
    answer: 1,
    explanationEs: 'En CI/CD se debe usar ejecución no interactiva con límites de turnos, costo, tiempo y permisos. Esto reduce el riesgo de automatización fuera de control.',
    vocabulary: { runaway: 'fuera de control', timeout: 'tiempo máximo', limits: 'límites' },
  },
  {
    id: 'q21',
    topicId: 'review-config',
    prompt: 'An automated reviewer repeatedly flags code that is explicitly allowed by the project architecture. What is the MOST effective correction?',
    options: [
      'Increase the model temperature.',
      'Add the project conventions and accepted exceptions to the reviewer configuration, keep tools restricted, and return structured findings.',
      'Ask the reviewer to report more issues.',
      'Remove all severity levels from the output.',
    ],
    answer: 1,
    explanationEs: 'El revisor necesita las reglas reales del proyecto y las excepciones aceptadas. Además, herramientas restringidas y una salida estructurada hacen el resultado más seguro y consumible.',
    vocabulary: { repeatedly: 'repetidamente', allowed: 'permitido', correction: 'corrección' },
  },
  {
    id: 'q22',
    topicId: 'test-generation',
    prompt: 'Claude Code is asked to generate tests for a legacy payment service. Which additional context will MOST improve test quality?',
    options: [
      'Only the production source file.',
      'A request to maximize the number of tests.',
      'Existing tests, fixture conventions, expected behaviors, failure cases, and important edge cases.',
      'Permission to rewrite the entire service before testing it.',
    ],
    answer: 2,
    explanationEs: 'Los tests existentes, fixtures, comportamientos esperados y casos límite permiten generar pruebas consistentes y útiles. Pedir cantidad sin contexto favorece aserciones triviales.',
    vocabulary: { legacy: 'heredado/antiguo', failure: 'fallo', 'edge case': 'caso límite' },
  },
  {
    id: 'q23',
    topicId: 'configuration',
    prompt: 'A coding rule should apply only to files matching src/payments/**/*.java. Where should this rule be configured?',
    options: [
      'In a global instruction that applies to every repository and file.',
      'In .claude/rules/ with an appropriate path glob.',
      'As a one-time chat message that is not saved.',
      'Inside an unrelated MCP server description.',
    ],
    answer: 1,
    explanationEs: 'Las reglas específicas por ruta deben configurarse en .claude/rules/ usando un glob. Así se aplican solo al conjunto de archivos correspondiente.',
    vocabulary: { matching: 'que coinciden con', apply: 'aplicar', appropriate: 'adecuado' },
  },
  {
    id: 'q24',
    topicId: 'structured',
    prompt: 'A downstream parser rejects any response that does not exactly match a required JSON schema. Which approach is MOST reliable?',
    options: [
      'Ask for JSON in plain language and parse any extra prose later.',
      'Use tool use with the JSON schema and force the tool call when the structured response is mandatory.',
      'Prefill the first curly brace and assume the rest will be valid.',
      'Use a regular expression to recover fields from free-form text.',
    ],
    answer: 1,
    explanationEs: 'Tool use con JSON Schema es más confiable que solicitar JSON en texto libre. Si la salida estructurada es obligatoria, tool_choice puede forzar la llamada.',
    vocabulary: { rejects: 'rechaza', exactly: 'exactamente', mandatory: 'obligatorio' },
  },
  {
    id: 'q25',
    topicId: 'schema',
    prompt: 'A form may omit apartment_number, while cancellation_reason may be explicitly null, and status must be one of active, inactive, or unknown. Which schema design is BEST?',
    options: [
      'Require every field and replace missing values with empty strings.',
      'Make apartment_number optional, cancellation_reason nullable, and status a constrained enum.',
      'Store every value in one unrestricted text field.',
      'Remove status validation to avoid rejected records.',
    ],
    answer: 1,
    explanationEs: 'Optional representa un campo que puede faltar; nullable permite null como valor válido; enum restringe status a valores controlados, incluyendo unknown.',
    vocabulary: { omit: 'omitir', explicitly: 'explícitamente', constrained: 'restringido' },
  },
  {
    id: 'q26',
    topicId: 'truncation',
    prompt: 'A structured security review of 500 files repeatedly ends with truncated JSON. What is the BEST remediation?',
    options: [
      'Increase max_tokens indefinitely and keep one request.',
      'Remove the schema and return unrestricted prose.',
      'Review smaller file batches, produce valid partial structures, and merge them deterministically.',
      'Discard findings from files processed before the truncation.',
    ],
    answer: 2,
    explanationEs: 'Dividir la revisión en lotes pequeños permite obtener estructuras parciales válidas. Luego se fusionan de manera determinista sin depender de una salida gigantesca.',
    vocabulary: { repeatedly: 'repetidamente', truncated: 'truncado/cortado', batches: 'lotes' },
  },
  {
    id: 'q27',
    topicId: 'extraction',
    prompt: 'An extraction pipeline returns inconsistent date and currency formats across similar invoices. Which change is MOST likely to improve consistency?',
    options: [
      'Raise the temperature and remove examples.',
      'Add representative few-shot examples, explicit normalization rules, and schema fields for missing values.',
      'Combine the entire invoice into one free-form string.',
      'Reject every invoice that contains an optional field.',
    ],
    answer: 1,
    explanationEs: 'Ejemplos representativos, reglas explícitas de normalización y un esquema que represente datos ausentes mejoran la consistencia de la extracción.',
    vocabulary: { across: 'a través de/entre', likely: 'probable', missing: 'faltante' },
  },
  {
    id: 'q28',
    topicId: 'builtin-tools',
    prompt: 'You need to find every YAML file, locate occurrences of timeout inside those files, and inspect the relevant sections. Which tool sequence is BEST?',
    options: [
      'Bash, Bash, Bash.',
      'Read, Glob, Grep.',
      'Glob, Grep, Read.',
      'Grep, Read, Glob.',
    ],
    answer: 2,
    explanationEs: 'Glob localiza archivos por ruta o nombre, Grep busca contenido y Read abre las secciones relevantes. Esa secuencia reduce exploración innecesaria.',
    vocabulary: { occurrences: 'apariciones', inspect: 'inspeccionar', relevant: 'relevante' },
  },
  {
    id: 'q29',
    topicId: 'tool-distribution',
    prompt: 'A synthesis agent only needs to read completed findings and produce a final report. Which tool assignment follows the principle of least privilege?',
    options: [
      'Give it every read, write, deployment, and deletion tool available.',
      'Give it only the read access and reporting capabilities required for synthesis.',
      'Give it production write access in case it discovers an issue.',
      'Give it no access to the findings and ask it to infer them.',
    ],
    answer: 1,
    explanationEs: 'El agente de síntesis debe recibir solo las herramientas necesarias para leer resultados y producir el informe. Esto reduce complejidad y acciones fuera de rol.',
    vocabulary: { assignment: 'asignación', 'least privilege': 'mínimo privilegio', required: 'requerido' },
  },
  {
    id: 'q30',
    topicId: 'tool-choice',
    prompt: 'An agent must retrieve an account_id before it can request that account\'s transactions. Which execution plan is CORRECT?',
    options: [
      'Call both tools in parallel because two calls are always faster.',
      'Retrieve the account_id first, then call the transactions tool with that result.',
      'Skip the account lookup and invent an identifier.',
      'Force the transactions tool before the required input exists.',
    ],
    answer: 1,
    explanationEs: 'La segunda llamada depende del account_id producido por la primera. Por eso deben ejecutarse en secuencia, no en paralelo.',
    vocabulary: { retrieve: 'recuperar', before: 'antes de', depends: 'depende' },
  },
]
