import type { Question } from './data'

export const claudeApiQuestionsPart2: Question[] = [
  {
    id: 'q116',
    topicId: 'specialized-review',
    prompt: 'A single review prompt must check security, business logic, compliance, performance, and style. Important issues are frequently missed. What is the BEST improvement?',
    options: [
      'Add more unrelated criteria to the same prompt.',
      'Use specialized review passes for the major concerns, then synthesize and deduplicate the findings.',
      'Increase temperature and keep the same architecture.',
      'Remove all output structure.',
    ],
    answer: 1,
    explanationEs: 'Separar preocupaciones reduce competencia entre criterios. Una síntesis posterior combina resultados, elimina duplicados y conserva desacuerdos.',
    vocabulary: {},
  },
  {
    id: 'q117',
    topicId: 'specialized-review',
    prompt: 'What makes two review passes genuinely specialized?',
    options: [
      'They use the same prompt but have different agent names.',
      'They have different goals, criteria, examples, tools, and output fields for their concerns.',
      'They always use different model temperatures.',
      'They process the same concern twice without changing instructions.',
    ],
    answer: 1,
    explanationEs: 'La especialización real modifica el objetivo y el contrato de cada pasada. Cambiar solo el nombre no cambia el comportamiento esperado.',
    vocabulary: {},
  },
  {
    id: 'q118',
    topicId: 'specialized-review',
    prompt: 'Three specialist reviewers report the same authorization flaw with different evidence. What should the synthesis step do?',
    options: [
      'Publish three independent findings without comparison.',
      'Keep only the shortest finding.',
      'Create one consolidated finding while preserving the strongest evidence and source references.',
      'Discard the flaw because the reviewers duplicated it.',
    ],
    answer: 2,
    explanationEs: 'La síntesis debe deduplicar el problema sin perder evidencia, fuentes ni la señal de que varios revisores coincidieron.',
    vocabulary: {},
  },
  {
    id: 'q119',
    topicId: 'specialized-review',
    prompt: 'Which task is LEAST likely to benefit from several specialized review agents?',
    options: [
      'A high-risk contract review with legal, privacy, and financial criteria.',
      'A large code change requiring separate security and logic analysis.',
      'A trivial read-only wording change with one clear acceptance criterion.',
      'A regulated workflow with independent compliance checks.',
    ],
    answer: 2,
    explanationEs: 'Una tarea trivial con un único criterio no justifica el costo y la coordinación de múltiples revisores especializados.',
    vocabulary: {},
  },

  {
    id: 'q120',
    topicId: 'tool-schema',
    prompt: 'A create_payment tool cannot operate without amount, currency, merchant_id, and idempotency_key. How should its schema represent those fields?',
    options: [
      'As optional free-form strings.',
      'As required fields with appropriate types and descriptions.',
      'As one unstructured notes field.',
      'Outside the schema in a natural-language comment only.',
    ],
    answer: 1,
    explanationEs: 'Los campos indispensables deben declararse required y usar tipos precisos. Esto detecta argumentos incompletos antes de ejecutar la operación.',
    vocabulary: {},
  },
  {
    id: 'q121',
    topicId: 'tool-schema',
    prompt: 'When is forcing a specific tool with tool_choice MOST appropriate?',
    options: [
      'When the model must decide among several unrelated operations.',
      'When a known tool invocation is mandatory for the required structured result.',
      'Whenever tools are available, regardless of the request.',
      'When the tool schema is incomplete.',
    ],
    answer: 1,
    explanationEs: 'Forzar una tool es útil cuando la llamada concreta es obligatoria. Si la selección depende de la solicitud, conviene permitir elección.',
    vocabulary: {},
  },
  {
    id: 'q122',
    topicId: 'tool-schema',
    prompt: 'A tool call passes JSON Schema validation, but the account_id belongs to another customer. What does this demonstrate?',
    options: [
      'Schema validation automatically guarantees authorization.',
      'Structural validation must be followed by business-rule and authorization checks.',
      'The account_id should always be an unrestricted string.',
      'tool_choice should be disabled permanently.',
    ],
    answer: 1,
    explanationEs: 'El schema valida forma y tipos, no propiedad, permisos ni reglas de negocio. El servidor debe realizar esas comprobaciones.',
    vocabulary: {},
  },
  {
    id: 'q123',
    topicId: 'tool-schema',
    prompt: 'Which tool description is MOST useful to the model?',
    options: [
      'A powerful enterprise tool.',
      'Searches users by email or organization filters; use get_user instead when an exact user ID is known.',
      'Use this whenever possible.',
      'Returns data and performs actions.',
    ],
    answer: 1,
    explanationEs: 'La descripción útil explica propósito, inputs y diferencia frente a herramientas similares, lo que mejora la selección correcta.',
    vocabulary: {},
  },

  {
    id: 'q124',
    topicId: 'truncation',
    prompt: 'A structured review of 2,000 files repeatedly ends with invalid JSON because the output is cut off. What is the BEST remediation?',
    options: [
      'Increase max_tokens indefinitely.',
      'Remove the schema and return free-form prose.',
      'Split the files into smaller batches, validate each result, and merge them deterministically.',
      'Retry the same request without limits until it succeeds.',
    ],
    answer: 2,
    explanationEs: 'La partición produce resultados parciales válidos y escalables. La fusión determinista evita depender de una única salida enorme.',
    vocabulary: {},
  },
  {
    id: 'q125',
    topicId: 'truncation',
    prompt: 'Which signal MOST directly indicates that a response may have been truncated?',
    options: [
      'The response contains an array.',
      'The stop reason reports a token limit or the expected completion marker is missing.',
      'The model used a tool.',
      'The first item is valid JSON.',
    ],
    answer: 1,
    explanationEs: 'El stop reason, el parsing y los marcadores de completitud permiten detectar si la salida terminó antes de completar el trabajo.',
    vocabulary: {},
  },
  {
    id: 'q126',
    topicId: 'truncation',
    prompt: 'One batch in a 20-batch extraction fails validation. What is the MOST efficient retry strategy?',
    options: [
      'Restart all 20 batches.',
      'Retry only the failed batch, with a smaller size if it truncates again.',
      'Ignore the failed batch and mark the extraction complete.',
      'Merge the invalid JSON without validation.',
    ],
    answer: 1,
    explanationEs: 'Los lotes independientes permiten reintentos selectivos. Si vuelve a truncarse, debe reducirse o subdividirse.',
    vocabulary: {},
  },
  {
    id: 'q127',
    topicId: 'truncation',
    prompt: 'What information should each partial structured result include to support reliable merging and retries?',
    options: [
      'Only the generated prose summary.',
      'Batch identity, source references, completion state, and structured items.',
      'Only the model temperature.',
      'A copy of every previous batch response.',
    ],
    answer: 1,
    explanationEs: 'Identidad del lote, fuentes y estado de completitud permiten fusionar, auditar y reintentar sin duplicar trabajo.',
    vocabulary: {},
  },

  {
    id: 'q128',
    topicId: 'extraction',
    prompt: 'A document does not contain a middle name. What should an extraction system do?',
    options: [
      'Invent a likely middle name to satisfy the schema.',
      'Represent the field as absent or null according to the defined contract.',
      'Copy the last name into the middle-name field.',
      'Reject every document without that field.',
    ],
    answer: 1,
    explanationEs: 'El schema debe representar ausencia. Completar campos faltantes con valores plausibles produce datos falsos.',
    vocabulary: {},
  },
  {
    id: 'q129',
    topicId: 'extraction',
    prompt: 'Which output BEST preserves normalization traceability for a date?',
    options: [
      'Only the normalized date with no evidence.',
      'The raw text, normalized ISO date, source location, and confidence.',
      'A guessed date and no source.',
      'A prose statement that the date looked valid.',
    ],
    answer: 1,
    explanationEs: 'Conservar valor original, normalizado, ubicación y confianza permite auditar la transformación y detectar errores.',
    vocabulary: {},
  },
  {
    id: 'q130',
    topicId: 'extraction',
    prompt: 'What kind of few-shot examples are MOST useful for a varied extraction task?',
    options: [
      'Many nearly identical easy examples.',
      'A diverse set covering common formats, missing data, ambiguity, and boundary cases.',
      'Only examples with every field present.',
      'Examples unrelated to the schema.',
    ],
    answer: 1,
    explanationEs: 'La diversidad enseña decisiones difíciles y formatos distintos. La repetición de casos fáciles consume contexto sin ampliar cobertura.',
    vocabulary: {},
  },
  {
    id: 'q131',
    topicId: 'extraction',
    prompt: 'A field contains two contradictory values in the same document. What is the BEST extraction behavior?',
    options: [
      'Select one silently.',
      'Average the values.',
      'Preserve the conflict with evidence and mark it ambiguous or route it for review.',
      'Invent a third value that fits the schema.',
    ],
    answer: 2,
    explanationEs: 'La contradicción debe representarse explícitamente. Elegir sin evidencia oculta incertidumbre y reduce trazabilidad.',
    vocabulary: {},
  },

  {
    id: 'q132',
    topicId: 'false-positives',
    prompt: 'A code reviewer flags every use of string concatenation as SQL injection, including code that never reaches a query. What is the BEST improvement?',
    options: [
      'Disable all SQL injection checks.',
      'Require a verified path from untrusted input to a query sink and account for approved sanitizers.',
      'Raise every finding to critical severity.',
      'Report more style issues to balance the results.',
    ],
    answer: 1,
    explanationEs: 'Exigir evidencia causal y conocer sanitizadores aceptados reduce falsos positivos sin eliminar la categoría de riesgo.',
    vocabulary: {},
  },
  {
    id: 'q133',
    topicId: 'false-positives',
    prompt: 'Why should precision and recall be measured separately?',
    options: [
      'Because they are two names for the same metric.',
      'Because reducing false positives can also cause the system to miss real issues.',
      'Because recall measures latency only.',
      'Because precision is relevant only for structured outputs.',
    ],
    answer: 1,
    explanationEs: 'Un sistema puede mejorar precisión reportando muy poco y perder recall. Ambas métricas muestran lados distintos del desempeño.',
    vocabulary: {},
  },
  {
    id: 'q134',
    topicId: 'false-positives',
    prompt: 'Which feedback is MOST useful after identifying a false positive?',
    options: [
      'Be less noisy.',
      'Show the incorrect finding, explain the accepted project pattern, and provide the corrected decision rule.',
      'Return fewer findings next time.',
      'Lower confidence on every future result.',
    ],
    answer: 1,
    explanationEs: 'El ejemplo concreto y la regla correcta entregan una señal precisa para evitar repetir el mismo error.',
    vocabulary: {},
  },
  {
    id: 'q135',
    topicId: 'false-positives',
    prompt: 'Which strategy is LEAST safe for reducing false positives?',
    options: [
      'Add specific project conventions.',
      'Require source evidence for each finding.',
      'Exclude an entire vulnerability category because some alerts were noisy.',
      'Use labeled positive and negative evaluation cases.',
    ],
    answer: 2,
    explanationEs: 'Excluir una categoría completa puede eliminar alertas verdaderas. Las correcciones deben ser específicas y evaluadas.',
    vocabulary: {},
  },

  {
    id: 'q136',
    topicId: 'boundaries',
    prompt: 'A contract extraction prompt says only “find important statements.” Why is this likely to produce noisy results?',
    options: [
      'The instruction lacks explicit inclusion, exclusion, and boundary criteria.',
      'The prompt is written in English.',
      'Structured output cannot be used for contracts.',
      'The model must always receive every possible document.',
    ],
    answer: 0,
    explanationEs: '“Important” queda sin definición operativa. El sistema necesita categorías permitidas, excluidas y ejemplos de borde.',
    vocabulary: {},
  },
  {
    id: 'q137',
    topicId: 'boundaries',
    prompt: 'The task should include contractual obligations but exclude promotional language. Which prompt element BEST clarifies the boundary?',
    options: [
      'A request to be comprehensive.',
      'Positive, negative, and ambiguous examples near the category boundary.',
      'A higher temperature.',
      'A requirement to return the longest possible answer.',
    ],
    answer: 1,
    explanationEs: 'Los ejemplos cercanos a la frontera muestran cómo distinguir obligación, promoción y casos ambiguos.',
    vocabulary: {},
  },
  {
    id: 'q138',
    topicId: 'boundaries',
    prompt: 'A statement is relevant but ambiguous. What is the BEST treatment?',
    options: [
      'Force it into the included category.',
      'Silently exclude it.',
      'Represent it as uncertain or route it for review according to the workflow.',
      'Rewrite the source to remove ambiguity.',
    ],
    answer: 2,
    explanationEs: 'La ambigüedad debe conservarse o revisarse. Forzar una clasificación crea certeza que la evidencia no sostiene.',
    vocabulary: {},
  },
  {
    id: 'q139',
    topicId: 'boundaries',
    prompt: 'Which evaluation set BEST tests inclusion and exclusion boundaries?',
    options: [
      'Only obvious positive examples.',
      'Only examples the model has already seen.',
      'Clear inclusions, clear exclusions, and difficult boundary cases.',
      'A set containing no excluded items.',
    ],
    answer: 2,
    explanationEs: 'Los casos de frontera revelan si el sistema aprendió realmente el límite y no solo ejemplos fáciles.',
    vocabulary: {},
  },
]
