import type { Question } from './data'

export const agenticQuestionsPart2: Question[] = [
  {
    id: 'q16',
    topicId: 'dynamic-decomposition',
    prompt: 'A research agent discovers a new regulatory constraint halfway through its investigation. What is the MOST appropriate next step?',
    options: [
      'Ignore the finding until the original plan is complete.',
      'Restart the entire investigation from the beginning.',
      'Revise the task plan and add or reprioritize subtasks that address the new constraint.',
      'Continue with the original plan and mention the constraint only in the final summary.',
    ],
    answer: 2,
    explanationEs: 'La descomposición dinámica permite revisar el plan con nueva evidencia. No exige reiniciar ni terminar primero un plan que dejó de representar el problema.',
    vocabulary: {},
  },
  {
    id: 'q17',
    topicId: 'dynamic-decomposition',
    prompt: 'Which behavior BEST demonstrates dynamic task decomposition?',
    options: [
      'Executing every predefined subtask even after the root cause is confirmed.',
      'Creating, merging, or cancelling subtasks based on intermediate results.',
      'Avoiding an initial plan so the agent can improvise freely.',
      'Assigning every subtask to a different model.',
    ],
    answer: 1,
    explanationEs: 'El dinamismo consiste en adaptar las subtareas según resultados intermedios, pero manteniendo un objetivo, restricciones y control.',
    vocabulary: {},
  },
  {
    id: 'q18',
    topicId: 'dynamic-decomposition',
    prompt: 'A coordinator wants to prevent uncontrolled task expansion. Which constraint is MOST useful?',
    options: [
      'Never allow the plan to change.',
      'Limit the number of new subtasks and require each one to support a success criterion.',
      'Disable all checkpoints.',
      'Require every new subtask to repeat completed analysis.',
    ],
    answer: 1,
    explanationEs: 'Un límite de subtareas y una relación explícita con criterios de éxito permiten adaptación sin exploración infinita.',
    vocabulary: {},
  },
  {
    id: 'q19',
    topicId: 'dynamic-decomposition',
    prompt: 'Two planned subtasks now produce nearly identical evidence. What is the MOST efficient response?',
    options: [
      'Run both to completion because they were in the original plan.',
      'Cancel the entire workflow.',
      'Merge or deduplicate the work and preserve the useful evidence already collected.',
      'Discard all previous results and create two replacement tasks.',
    ],
    answer: 2,
    explanationEs: 'La descomposición dinámica permite fusionar trabajo redundante sin perder resultados válidos.',
    vocabulary: {},
  },

  {
    id: 'q20',
    topicId: 'review-architecture',
    prompt: 'A proposed change modifies production access permissions and requires human approval. Which workflow is MOST appropriate?',
    options: [
      'Direct execution because it minimizes latency.',
      'Plan mode or a multi-phase workflow with an explicit approval gate before execution.',
      'A single unconstrained subagent with write access.',
      'Parallel execution of planning and modification.',
    ],
    answer: 1,
    explanationEs: 'El riesgo, la baja reversibilidad y la aprobación obligatoria justifican separar análisis, revisión y ejecución.',
    vocabulary: {},
  },
  {
    id: 'q21',
    topicId: 'review-architecture',
    prompt: 'Which task is MOST suitable for direct execution?',
    options: [
      'Deleting a production database.',
      'Changing organization-wide security policies.',
      'Summarizing a local read-only configuration file.',
      'Publishing a legal decision without review.',
    ],
    answer: 2,
    explanationEs: 'Una tarea de lectura, simple y reversible es adecuada para ejecución directa.',
    vocabulary: {},
  },
  {
    id: 'q22',
    topicId: 'review-architecture',
    prompt: 'Why would a team choose a multi-phase workflow instead of one large prompt?',
    options: [
      'To guarantee that every stage uses the same tools and criteria.',
      'To separate responsibilities, use specialized criteria, persist state, and add approval gates.',
      'To remove the need for validation.',
      'To ensure the model never adapts to new information.',
    ],
    answer: 1,
    explanationEs: 'La separación por fases permite prompts, herramientas, validaciones y aprobaciones distintas para cada etapa.',
    vocabulary: {},
  },
  {
    id: 'q23',
    topicId: 'review-architecture',
    prompt: 'What is a common downside of using a multi-phase workflow for a trivial, reversible task?',
    options: [
      'It may add unnecessary latency and coordination complexity.',
      'It always reduces output quality.',
      'It prevents any human review.',
      'It cannot use structured outputs.',
    ],
    answer: 0,
    explanationEs: 'La arquitectura debe ser proporcional al riesgo. Demasiadas fases pueden añadir costo sin un beneficio real.',
    vocabulary: {},
  },

  {
    id: 'q24',
    topicId: 'state',
    prompt: 'Which information should a durable checkpoint contain for a resumable multi-agent workflow?',
    options: [
      'Only the original user prompt.',
      'Completed and pending tasks, structured outputs, source references, errors, retries, and approvals.',
      'Only the latest model response.',
      'Only the model name and temperature.',
    ],
    answer: 1,
    explanationEs: 'Un checkpoint útil debe representar el progreso operativo completo, no solo el contexto conversacional.',
    vocabulary: {},
  },
  {
    id: 'q25',
    topicId: 'state',
    prompt: 'A workflow may retry a payment-creation step after a crash. What is MOST important for preventing duplicates?',
    options: [
      'A larger context window.',
      'A higher model temperature.',
      'An idempotency key or equivalent deduplication mechanism.',
      'Repeating the original prompt exactly.',
    ],
    answer: 2,
    explanationEs: 'La idempotencia o deduplicación evita repetir efectos externos cuando una fase se reintenta.',
    vocabulary: {},
  },
  {
    id: 'q26',
    topicId: 'state',
    prompt: 'After resuming a repository analysis, only three files have changed. What is the MOST efficient strategy?',
    options: [
      'Discard all previous findings and start over.',
      'Reanalyze the changed files and reuse the persisted state for unchanged work.',
      'Repeat every tool call from the previous session.',
      'Use only the final summary and ignore source references.',
    ],
    answer: 1,
    explanationEs: 'La reanudación eficiente reutiliza resultados válidos y revisa solo lo que cambió.',
    vocabulary: {},
  },
  {
    id: 'q27',
    topicId: 'state',
    prompt: 'Why should large artifacts usually be stored outside the checkpoint itself?',
    options: [
      'Because checkpoints cannot contain references.',
      'To keep the checkpoint compact while preserving artifact locations, hashes, and metadata.',
      'Because external artifacts never need versioning.',
      'To avoid recording where the data came from.',
    ],
    answer: 1,
    explanationEs: 'El checkpoint puede conservar referencias y hashes mientras el artefacto grande vive en almacenamiento externo.',
    vocabulary: {},
  },

  {
    id: 'q28',
    topicId: 'orchestration',
    prompt: 'Four independent domain searches must complete before a final synthesis. Which orchestration pattern BEST minimizes latency?',
    options: [
      'Run every search sequentially and synthesize after each one.',
      'Run the searches in parallel, then send all results to a synthesis step.',
      'Run synthesis before the searches.',
      'Use one worker and prohibit specialization.',
    ],
    answer: 1,
    explanationEs: 'Las búsquedas son independientes y pueden ejecutarse en paralelo; la síntesis depende de todas.',
    vocabulary: {},
  },
  {
    id: 'q29',
    topicId: 'orchestration',
    prompt: 'A transaction lookup requires an account ID returned by another tool. How should the calls be orchestrated?',
    options: [
      'Call both tools in parallel.',
      'Call the transaction tool first with a guessed ID.',
      'Call the account lookup first, then use its output in the transaction call.',
      'Avoid tool use and answer from memory.',
    ],
    answer: 2,
    explanationEs: 'Existe una dependencia de datos, por lo que las llamadas deben ejecutarse secuencialmente.',
    vocabulary: {},
  },
  {
    id: 'q30',
    topicId: 'orchestration',
    prompt: 'What is the PRIMARY role of a synthesis agent after several specialist reviews?',
    options: [
      'Repeat every specialist analysis from scratch.',
      'Combine findings, remove duplicates, preserve sources, and represent disagreements accurately.',
      'Discard uncertain findings automatically.',
      'Choose the longest specialist response as the final answer.',
    ],
    answer: 1,
    explanationEs: 'La síntesis combina evidencia sin borrar trazabilidad, incertidumbre ni desacuerdos.',
    vocabulary: {},
  },
  {
    id: 'q31',
    topicId: 'orchestration',
    prompt: 'Which statement about multi-agent orchestration is LEAST accurate?',
    options: [
      'Parallel execution is useful for independent tasks.',
      'Sequential execution is necessary when one task depends on another output.',
      'Adding more agents always improves quality and reduces cost.',
      'A coordinator can distribute work and combine specialist results.',
    ],
    answer: 2,
    explanationEs: 'Más agentes añaden coordinación, costo y posibles inconsistencias; no garantizan una mejor solución.',
    vocabulary: {},
  },
]
