import type { Question } from './data'

export const agenticQuestionsPart3: Question[] = [
  {
    id: 'q32',
    topicId: 'parallel',
    prompt: 'A coordinator must retrieve weather, exchange-rate, and holiday information before producing one summary. The three lookups are independent. Which plan BEST minimizes latency?',
    options: [
      'Run each lookup sequentially and summarize after every result.',
      'Run all three lookups in parallel, then synthesize the results.',
      'Generate the summary before calling any tools.',
      'Use a larger context window instead of parallel calls.',
    ],
    answer: 1,
    explanationEs: 'Las tres consultas pueden comenzar con el contexto actual y no dependen entre sí. Ejecutarlas en paralelo reduce la latencia acumulada; la síntesis ocurre después.',
    vocabulary: {},
  },
  {
    id: 'q33',
    topicId: 'parallel',
    prompt: 'A transaction tool requires an account_id returned by a customer lookup. How should the calls be executed?',
    options: [
      'Call both tools in parallel and let the transaction tool guess the ID.',
      'Call the transaction tool first to reduce latency.',
      'Call the customer lookup first, then pass its account_id to the transaction tool.',
      'Avoid tools and answer from prior model knowledge.',
    ],
    answer: 2,
    explanationEs: 'La segunda llamada necesita un dato producido por la primera, por lo que existe una dependencia de datos y la ejecución debe ser secuencial.',
    vocabulary: {},
  },
  {
    id: 'q34',
    topicId: 'parallel',
    prompt: 'Which scenario is LEAST suitable for uncoordinated parallel execution?',
    options: [
      'Reading three independent public documents.',
      'Searching separate log indexes for the same time window.',
      'Updating the same production record from multiple agents.',
      'Retrieving independent product descriptions.',
    ],
    answer: 2,
    explanationEs: 'Varias escrituras sobre el mismo estado pueden generar condiciones de carrera o resultados inconsistentes. Requieren coordinación o secuenciación.',
    vocabulary: {},
  },
  {
    id: 'q35',
    topicId: 'parallel',
    prompt: 'What is the PRIMARY benefit of issuing multiple independent tool calls in one iteration?',
    options: [
      'It guarantees that every result is correct.',
      'It reduces total latency by avoiding unnecessary sequential waits.',
      'It removes the need for a synthesis step.',
      'It ensures the tools return identical formats.',
    ],
    answer: 1,
    explanationEs: 'El beneficio principal es de latencia. El paralelismo no garantiza precisión, formatos idénticos ni elimina la necesidad de sintetizar.',
    vocabulary: {},
  },

  {
    id: 'q36',
    topicId: 'session-resumption',
    prompt: 'A repository review resumes after only two files changed. Which strategy is MOST efficient?',
    options: [
      'Discard every previous finding and reread the entire repository.',
      'Reuse valid persisted findings and reanalyze the changed files plus any affected conclusions.',
      'Repeat every previous tool call in the same order.',
      'Use only the old final summary and ignore the changed files.',
    ],
    answer: 1,
    explanationEs: 'La reanudación eficiente reutiliza trabajo vigente y analiza cambios e impactos. No repite todo ni ignora modificaciones.',
    vocabulary: {},
  },
  {
    id: 'q37',
    topicId: 'session-resumption',
    prompt: 'Which metadata is MOST useful for determining whether a prior file analysis is still valid?',
    options: [
      'The model temperature used in the previous session.',
      'The number of messages in the conversation.',
      'A file hash, version, or commit identifier.',
      'The length of the prior final answer.',
    ],
    answer: 2,
    explanationEs: 'Hashes, versiones o commits permiten comparar el artefacto analizado con su estado actual y decidir si el resultado sigue vigente.',
    vocabulary: {},
  },
  {
    id: 'q38',
    topicId: 'session-resumption',
    prompt: 'What should a resumed session receive instead of the entire historical conversation?',
    options: [
      'Only the original user request.',
      'A compact operational state containing decisions, findings, sources, progress, and pending work.',
      'Only the last assistant message.',
      'No prior information so the model remains unbiased.',
    ],
    answer: 1,
    explanationEs: 'El estado compacto reconstruye el contexto operativo sin consumir tokens con cada detalle histórico.',
    vocabulary: {},
  },
  {
    id: 'q39',
    topicId: 'session-resumption',
    prompt: 'A central policy document changed after a previous review. What should the system do before reusing dependent findings?',
    options: [
      'Assume every old finding remains valid because the source filename is unchanged.',
      'Evaluate which conclusions depended on that document and invalidate or recheck them as needed.',
      'Delete all state from every unrelated workflow.',
      'Increase max_tokens and keep the previous conclusions unchanged.',
    ],
    answer: 1,
    explanationEs: 'Un cambio en una premisa central puede invalidar conclusiones dependientes. La trazabilidad permite identificar qué debe revisarse.',
    vocabulary: {},
  },

  {
    id: 'q40',
    topicId: 'subagent-tools',
    prompt: 'A subagent is responsible only for read-only code review. Which tool set is MOST appropriate?',
    options: [
      'Read, Glob, and Grep, without repository write or deployment tools.',
      'All available tools, including production administration.',
      'Only a deployment tool.',
      'Edit and shell access but no reading tools.',
    ],
    answer: 0,
    explanationEs: 'El rol de revisión necesita lectura y búsqueda. Permisos de escritura o despliegue no contribuyen al objetivo y aumentan el riesgo.',
    vocabulary: {},
  },
  {
    id: 'q41',
    topicId: 'subagent-tools',
    prompt: 'What is the PRIMARY reason to restrict tools for specialized subagents?',
    options: [
      'To make every prompt shorter than one sentence.',
      'To reduce irrelevant choices and prevent actions outside the assigned role.',
      'To guarantee that no tool call can fail.',
      'To prevent the coordinator from receiving results.',
    ],
    answer: 1,
    explanationEs: 'Las restricciones reducen complejidad de decisión, superficie de error y acciones fuera de alcance. No eliminan todos los fallos.',
    vocabulary: {},
  },
  {
    id: 'q42',
    topicId: 'subagent-tools',
    prompt: 'A prompt asks a read-only reviewer to modify files and deploy the fix. What is the MOST important design problem?',
    options: [
      'The prompt is too short.',
      'The role, authorized tools, and requested outcome are inconsistent.',
      'The model needs a higher temperature.',
      'The reviewer should receive more unrelated context.',
    ],
    answer: 1,
    explanationEs: 'El objetivo solicita acciones incompatibles con el rol y permisos. Deben alinearse objetivo, herramientas, contexto y salida.',
    vocabulary: {},
  },
  {
    id: 'q43',
    topicId: 'subagent-tools',
    prompt: 'Which configuration BEST enforces separation of duties in a high-risk workflow?',
    options: [
      'One agent analyzes, approves, and executes its own production change.',
      'A reviewer produces a recommendation, a human or separate reviewer approves it, and a different component executes it.',
      'Every agent receives the same production credentials.',
      'The coordinator skips validation to reduce latency.',
    ],
    answer: 1,
    explanationEs: 'Separar análisis, aprobación y ejecución reduce el riesgo de que un mismo agente controle todo el proceso sin revisión independiente.',
    vocabulary: {},
  },

  {
    id: 'q44',
    topicId: 'spawn-diagnostics',
    prompt: 'A coordinator requests a subagent by an identifier that is not registered. What should be checked FIRST?',
    options: [
      'The model temperature.',
      'The agent definition, registration, and referenced identifier.',
      'The size of the final response.',
      'The color of the user interface.',
    ],
    answer: 1,
    explanationEs: 'Si el agente no puede crearse, primero se revisan definición, registro e identificador. La temperatura no corrige una referencia inexistente.',
    vocabulary: {},
  },
  {
    id: 'q45',
    topicId: 'spawn-diagnostics',
    prompt: 'A subagent starts successfully but receives “Read tool not authorized” on its first action. What is the MOST likely cause?',
    options: [
      'The final output schema is too detailed.',
      'The subagent tool allowlist or permissions are incomplete.',
      'The coordinator used too few tokens.',
      'The agent definition must be renamed.',
    ],
    answer: 1,
    explanationEs: 'El agente inició y entendió la tarea, pero la herramienta fue rechazada. El problema probable está en autorización o allowlist.',
    vocabulary: {},
  },
  {
    id: 'q46',
    topicId: 'spawn-diagnostics',
    prompt: 'A subagent definition exists, but spawning fails because a required repository parameter is missing. Where should the issue be corrected?',
    options: [
      'In the contract between the coordinator and the subagent invocation.',
      'By increasing temperature.',
      'By granting unrelated production permissions.',
      'By removing all required parameters from the definition.',
    ],
    answer: 0,
    explanationEs: 'La llamada no cumple el contrato de entrada. Debe corregirse la invocación o validación entre coordinador y subagente.',
    vocabulary: {},
  },
  {
    id: 'q47',
    topicId: 'spawn-diagnostics',
    prompt: 'Which action is LEAST useful as the first response to a deterministic subagent spawning failure?',
    options: [
      'Inspect the exact error and logs.',
      'Validate registration, parameters, wiring, and permissions.',
      'Change model temperature without examining configuration.',
      'Check whether the requested tools are available to the subagent.',
    ],
    answer: 2,
    explanationEs: 'Cambiar temperatura no resuelve definiciones faltantes, contratos inválidos ni permisos bloqueados. Primero se revisa evidencia y configuración.',
    vocabulary: {},
  },
]
