import type { Question } from './data'

export const claudeApiQuestionsPart1: Question[] = [
  {
    id: 'q96',
    topicId: 'human-review',
    prompt: 'Which routing strategy BEST concentrates human review on the cases that need it most?',
    options: [
      'Review a random 10% of all outputs and use no other rule.',
      'Route low-confidence, ambiguous, unusual, or high-risk cases to reviewers.',
      'Review only the shortest documents.',
      'Review only outputs produced late in the day.',
    ],
    answer: 1,
    explanationEs: 'La revisión dirigida por confianza, ambigüedad, novedad y riesgo concentra el esfuerzo humano donde el error es más probable o costoso.',
    vocabulary: {},
  },
  {
    id: 'q97',
    topicId: 'human-review',
    prompt: 'A model is highly confident that an account should be permanently closed. Company policy requires approval for irreversible actions. What should happen?',
    options: [
      'Close the account automatically because confidence is high.',
      'Ignore the policy if the model has performed well historically.',
      'Route the decision for required human approval before execution.',
      'Lower the temperature and execute immediately.',
    ],
    answer: 2,
    explanationEs: 'El alto impacto y la política de aprobación prevalecen sobre la confianza del modelo. Riesgo y confianza son dimensiones distintas.',
    vocabulary: {},
  },
  {
    id: 'q98',
    topicId: 'human-review',
    prompt: 'Only one extracted field is ambiguous while the rest of the document passed validation. What is the MOST efficient review design?',
    options: [
      'Require the reviewer to redo the entire document.',
      'Route only the ambiguous field with its source evidence and alternatives.',
      'Discard the document automatically.',
      'Accept the ambiguous field without review.',
    ],
    answer: 1,
    explanationEs: 'La revisión a nivel de campo reduce trabajo humano y conserva las partes ya validadas del documento.',
    vocabulary: {},
  },
  {
    id: 'q99',
    topicId: 'human-review',
    prompt: 'Why is random sampling alone insufficient as a human-review strategy?',
    options: [
      'It cannot estimate overall quality.',
      'It does not reliably prioritize the most ambiguous or high-risk cases.',
      'It always reviews every output.',
      'It prevents reviewers from seeing source documents.',
    ],
    answer: 1,
    explanationEs: 'El muestreo aleatorio puede medir calidad global, pero no garantiza revisar los casos con mayor riesgo o incertidumbre.',
    vocabulary: {},
  },
  {
    id: 'q100',
    topicId: 'human-review',
    prompt: 'What information is MOST useful to a human reviewer?',
    options: [
      'Only the model name.',
      'The proposed decision, relevant source evidence, escalation reason, and allowed actions.',
      'Only the final confidence number with no context.',
      'The complete history of unrelated requests.',
    ],
    answer: 1,
    explanationEs: 'La persona necesita comprender la propuesta, la evidencia, por qué fue escalada y qué decisiones puede tomar.',
    vocabulary: {},
  },

  {
    id: 'q101',
    topicId: 'batches',
    prompt: 'A company needs to classify 50,000 independent documents overnight. Immediate responses are not required. Which option is MOST appropriate?',
    options: [
      'One interactive chat session.',
      'Synchronous Messages API calls that block a user interface.',
      'Message Batches with stable identifiers for each document.',
      'One prompt containing all documents regardless of context limits.',
    ],
    answer: 2,
    explanationEs: 'El trabajo es voluminoso, independiente y tolerante a espera, por lo que un batch asíncrono es la opción adecuada.',
    vocabulary: {},
  },
  {
    id: 'q102',
    topicId: 'batches',
    prompt: 'An interactive assistant must answer the user before the next screen can load. Which API mode is MOST appropriate?',
    options: [
      'Message Batches.',
      'Messages API.',
      'An overnight scheduler.',
      'A batch that is polled once per day.',
    ],
    answer: 1,
    explanationEs: 'La aplicación necesita una respuesta inmediata dentro del flujo actual, por lo que corresponde usar Messages API.',
    vocabulary: {},
  },
  {
    id: 'q103',
    topicId: 'batches',
    prompt: 'What is the PRIMARY purpose of a custom identifier on each batch request?',
    options: [
      'To increase model intelligence.',
      'To map each returned result to the original application record.',
      'To force results to be returned in submission order.',
      'To remove the need for error handling.',
    ],
    answer: 1,
    explanationEs: 'El identificador permite correlacionar resultados con documentos o tareas originales sin depender del orden de salida.',
    vocabulary: {},
  },
  {
    id: 'q104',
    topicId: 'batches',
    prompt: 'A batch contains 9,950 successful requests and 50 retryable failures. What is the BEST recovery strategy?',
    options: [
      'Discard all successful results and resubmit the entire batch.',
      'Process the successful items and retry only the failed requests with deduplication.',
      'Assume the failed requests succeeded.',
      'Convert the entire workload into one giant synchronous request.',
    ],
    answer: 1,
    explanationEs: 'Los resultados se evalúan por solicitud. Reintentar solo los fallos evita duplicar trabajo y reduce riesgo de aplicar resultados dos veces.',
    vocabulary: {},
  },
  {
    id: 'q105',
    topicId: 'batches',
    prompt: 'Which assumption about batch results is LEAST safe?',
    options: [
      'Each request should have a stable application identifier.',
      'Individual requests may have different outcomes.',
      'Returned results will always match the original submission order.',
      'The application should persist the batch state.',
    ],
    answer: 2,
    explanationEs: 'La aplicación debe correlacionar por identificador y no depender del orden de los resultados.',
    vocabulary: {},
  },

  {
    id: 'q106',
    topicId: 'structured',
    prompt: 'A downstream system fails unless every response follows a mandatory schema. Which method is MOST reliable?',
    options: [
      'Ask for JSON in natural language and parse any braces with a regex.',
      'Use tool use with a JSON Schema and validate the returned structure.',
      'Accept free-form prose and infer fields later.',
      'Increase temperature until the format looks correct.',
    ],
    answer: 1,
    explanationEs: 'Tool use con JSON Schema entrega un contrato estructurado más fuerte que una solicitud de JSON en prosa. La aplicación debe validar el resultado igualmente.',
    vocabulary: {},
  },
  {
    id: 'q107',
    topicId: 'structured',
    prompt: 'A response passes JSON Schema validation, but the invoice total does not equal the sum of its line items. What is missing?',
    options: [
      'A larger context window.',
      'Business or semantic validation after structural validation.',
      'A less specific schema.',
      'A random retry with no error message.',
    ],
    answer: 1,
    explanationEs: 'La estructura puede ser válida mientras el contenido viola reglas del dominio. Se necesita validación semántica o de negocio.',
    vocabulary: {},
  },
  {
    id: 'q108',
    topicId: 'structured',
    prompt: 'A large structured review repeatedly truncates before producing valid output. What is the BEST remediation?',
    options: [
      'Remove all validation.',
      'Increase output limits indefinitely.',
      'Split the work into smaller calls and merge valid partial structures deterministically.',
      'Switch to unstructured prose and stop checking completeness.',
    ],
    answer: 2,
    explanationEs: 'Dividir el trabajo produce estructuras parciales completas y permite una fusión controlada, en lugar de depender de una salida enorme.',
    vocabulary: {},
  },
  {
    id: 'q109',
    topicId: 'structured',
    prompt: 'A structured response fails validation because one required field is missing. Which retry prompt is MOST useful?',
    options: [
      'Try again.',
      'Be more careful.',
      'Provide the exact validation error and restate the required field and expected schema.',
      'Use a different writing style.',
    ],
    answer: 2,
    explanationEs: 'El error exacto entrega una señal concreta para corregir la estructura. Los reintentos vagos suelen repetir el mismo problema.',
    vocabulary: {},
  },
  {
    id: 'q110',
    topicId: 'structured',
    prompt: 'Why should structured data and human-readable explanation often use separate fields?',
    options: [
      'So the schema can contain arbitrary prose inside numeric values.',
      'So automated consumers receive stable fields while people still receive understandable context.',
      'So validation can be skipped.',
      'So every field can be optional.',
    ],
    answer: 1,
    explanationEs: 'Separar datos y explicación evita contaminar campos comparables y permite atender a consumidores automáticos y humanos.',
    vocabulary: {},
  },

  {
    id: 'q111',
    topicId: 'schema',
    prompt: 'A document may not contain a middle name. Which schema choice BEST represents that condition?',
    options: [
      'Require the field and invent a value.',
      'Make the field optional when omission is valid.',
      'Require an arbitrary empty string in every case.',
      'Store the entire document as one unrestricted string.',
    ],
    answer: 1,
    explanationEs: 'Optional representa que la propiedad puede no aparecer. No se debe inventar un valor para satisfacer el schema.',
    vocabulary: {},
  },
  {
    id: 'q112',
    topicId: 'schema',
    prompt: 'A field must always be present, but its value may legitimately be unknown. Which design is MOST appropriate?',
    options: [
      'Required and nullable, when null is an accepted domain value.',
      'Optional only, with no distinction between missing and unknown.',
      'A required guessed value.',
      'An unrestricted object with no documented meaning.',
    ],
    answer: 0,
    explanationEs: 'Required controla presencia y nullable permite null como valor válido. Ambas condiciones pueden coexistir.',
    vocabulary: {},
  },
  {
    id: 'q113',
    topicId: 'schema',
    prompt: 'A status can be active, inactive, or impossible to determine from the source. What is the BEST representation?',
    options: [
      'A free-form string.',
      'A boolean that guesses between active and inactive.',
      'An enum containing active, inactive, and unknown.',
      'Always default to active.',
    ],
    answer: 2,
    explanationEs: 'El enum controla valores y unknown representa una clasificación no sustentada sin inventar una categoría.',
    vocabulary: {},
  },
  {
    id: 'q114',
    topicId: 'schema',
    prompt: 'How should a list of invoice line items usually be modeled?',
    options: [
      'As one comma-separated string.',
      'As an array whose items follow a defined object schema.',
      'As unrelated top-level fields with changing names.',
      'As free-form prose with no types.',
    ],
    answer: 1,
    explanationEs: 'Un array con item schema mantiene una estructura consistente para cada línea y facilita validación y procesamiento.',
    vocabulary: {},
  },
  {
    id: 'q115',
    topicId: 'schema',
    prompt: 'An identifier may contain leading zeros. Which type is MOST appropriate when those zeros are meaningful?',
    options: [
      'Integer, because every identifier is a number.',
      'String, so the exact identifier representation is preserved.',
      'Boolean.',
      'An array of random digits.',
    ],
    answer: 1,
    explanationEs: 'Los identificadores no siempre son cantidades. Un string conserva ceros iniciales y evita transformaciones numéricas indebidas.',
    vocabulary: {},
  },
]
