import type { Question } from './data'

export const mcpQuestionsPart1: Question[] = [
  {
    id: 'q140',
    topicId: 'builtin-tools',
    prompt: 'You need to locate every file matching **/config/*.yaml before inspecting their contents. Which built-in tool should be used FIRST?',
    options: ['Grep', 'Glob', 'Read', 'Bash'],
    answer: 1,
    explanationEs: 'Glob busca por patrón de nombre o ruta. Después puedes usar Grep o Read sobre los archivos encontrados.',
    vocabulary: {},
  },
  {
    id: 'q141',
    topicId: 'builtin-tools',
    prompt: 'After locating several YAML files, you need to find which ones contain the key retry_limit. What is the BEST next tool?',
    options: ['Glob again', 'Grep', 'Read every repository file', 'Bash with an unrestricted recursive command'],
    answer: 1,
    explanationEs: 'Grep busca texto dentro de los archivos candidatos y evita leer contenido irrelevante.',
    vocabulary: {},
  },
  {
    id: 'q142',
    topicId: 'builtin-tools',
    prompt: 'When is Bash MOST appropriate during codebase exploration?',
    options: [
      'Whenever any file must be located.',
      'Whenever text must be searched inside files.',
      'When a required command or operation has no safer built-in tool equivalent.',
      'As the default replacement for Glob, Grep, and Read.',
    ],
    answer: 2,
    explanationEs: 'Bash es apropiado para ejecutar comandos necesarios sin una herramienta incorporada equivalente, no como opción predeterminada para todo.',
    vocabulary: {},
  },
  {
    id: 'q143',
    topicId: 'builtin-tools',
    prompt: 'Which exploration sequence usually minimizes unnecessary context?',
    options: [
      'Read every file, then search filenames.',
      'Glob candidate files, Grep relevant content, then Read the necessary files.',
      'Run a shell command that prints the complete repository.',
      'Use Read before knowing which files are relevant.',
    ],
    answer: 1,
    explanationEs: 'La secuencia incremental localiza, filtra y finalmente inspecciona solo lo necesario.',
    vocabulary: {},
  },

  {
    id: 'q144',
    topicId: 'tool-distribution',
    prompt: 'A synthesis agent only combines findings from specialist reviewers. Which tool assignment is BEST?',
    options: [
      'Give it every read, write, deployment, and deletion tool.',
      'Give it structured reviewer outputs and only the tools needed to inspect supporting evidence.',
      'Give it production credentials in case they become useful.',
      'Give it the same tools as every other agent for consistency.',
    ],
    answer: 1,
    explanationEs: 'El sintetizador debe recibir solo capacidades necesarias para su función. Escritura y producción amplían el riesgo sin aportar al objetivo.',
    vocabulary: {},
  },
  {
    id: 'q145',
    topicId: 'tool-distribution',
    prompt: 'Why can a smaller tool set improve agent reliability?',
    options: [
      'It guarantees that every output is correct.',
      'It reduces irrelevant choices and prevents actions outside the agent role.',
      'It removes the need for tool descriptions.',
      'It lets the agent ignore authorization rules.',
    ],
    answer: 1,
    explanationEs: 'Menos herramientas irrelevantes reducen ambigüedad de selección y limitan acciones fuera del rol.',
    vocabulary: {},
  },
  {
    id: 'q146',
    topicId: 'tool-distribution',
    prompt: 'A reviewer should propose production permission changes but must not apply them. What is the BEST architecture?',
    options: [
      'Give the reviewer direct production write access.',
      'Separate proposal and execution, with approval before an authorized executor applies the change.',
      'Let the reviewer apply changes only when confidence is high.',
      'Provide all credentials but ask the reviewer not to use them.',
    ],
    answer: 1,
    explanationEs: 'Separar propuesta, aprobación y ejecución reduce impacto y aplica mínimo privilegio.',
    vocabulary: {},
  },
  {
    id: 'q147',
    topicId: 'tool-distribution',
    prompt: 'Which situation is the clearest violation of least privilege?',
    options: [
      'A read-only auditor can search and inspect logs.',
      'A deployment agent can deploy only to its assigned environment.',
      'Every subagent receives deletion and production tools regardless of its task.',
      'A reviewer can read the files it must evaluate.',
    ],
    answer: 2,
    explanationEs: 'Entregar herramientas destructivas o de producción a todos los agentes, sin relación con su tarea, viola mínimo privilegio.',
    vocabulary: {},
  },

  {
    id: 'q148',
    topicId: 'mcp-resources',
    prompt: 'An MCP server exposes a versioned architecture handbook that clients only need to discover and read. How should it usually be modeled?',
    options: ['As an MCP resource', 'As a destructive MCP tool', 'As a forced deployment tool', 'As an unrestricted shell command'],
    answer: 0,
    explanationEs: 'Un contenido direccionable y de lectura corresponde a un resource.',
    vocabulary: {},
  },
  {
    id: 'q149',
    topicId: 'mcp-resources',
    prompt: 'Which capability is MOST naturally represented as an MCP tool rather than a resource?',
    options: [
      'Reading a static policy document.',
      'Loading a reference schema by URI.',
      'Creating a support ticket with supplied fields.',
      'Browsing a versioned manual.',
    ],
    answer: 2,
    explanationEs: 'Crear un ticket es una operación invocable con inputs y efectos; corresponde a una tool.',
    vocabulary: {},
  },
  {
    id: 'q150',
    topicId: 'mcp-resources',
    prompt: 'A product catalog is available as static reference data, but users also need filtered searches. What is the BEST MCP design?',
    options: [
      'Expose only a destructive tool.',
      'Expose the catalog as a resource and the parameterized search as a tool.',
      'Put the entire catalog in every system prompt.',
      'Represent both operations as deployment tools.',
    ],
    answer: 1,
    explanationEs: 'El contenido estático puede ser resource y la búsqueda dinámica con parámetros puede ser tool.',
    vocabulary: {},
  },
  {
    id: 'q151',
    topicId: 'mcp-resources',
    prompt: 'What is a key benefit of representing large reference content as an MCP resource?',
    options: [
      'It automatically grants write permissions.',
      'It can be discovered and loaded only when relevant instead of being placed in every prompt.',
      'It forces the model to execute an action.',
      'It eliminates the need to track the source.',
    ],
    answer: 1,
    explanationEs: 'Los resources permiten recuperación selectiva y preservan una referencia identificable a la fuente.',
    vocabulary: {},
  },

  {
    id: 'q152',
    topicId: 'mcp-integration',
    prompt: 'After adding an MCP server configuration, what should be verified BEFORE assuming the integration is ready?',
    options: [
      'That the configuration file exists only.',
      'That the client connects and discovers the expected resources or tools.',
      'That credentials are committed to the repository.',
      'That every project can access the server globally.',
    ],
    answer: 1,
    explanationEs: 'La integración debe probar conexión y discovery; una configuración presente no demuestra que el cliente vea las capacidades.',
    vocabulary: {},
  },
  {
    id: 'q153',
    topicId: 'mcp-integration',
    prompt: 'An MCP integration works locally but fails in CI with an authentication error. What should be checked FIRST?',
    options: [
      'Increase model temperature.',
      'Whether the CI environment has the required secret and correct scope.',
      'Convert all resources into tools.',
      'Make the credentials public.',
    ],
    answer: 1,
    explanationEs: 'Una diferencia entre local y CI suele estar en secretos, variables de entorno o permisos del entorno.',
    vocabulary: {},
  },
  {
    id: 'q154',
    topicId: 'mcp-integration',
    prompt: 'Which credential practice is BEST for an MCP server used by a repository?',
    options: [
      'Hard-code the token in a committed configuration file.',
      'Use environment variables or a secret manager with the minimum required scope.',
      'Reuse a personal production token in every environment.',
      'Print the token in logs to simplify debugging.',
    ],
    answer: 1,
    explanationEs: 'Los secretos deben permanecer fuera del repositorio, con alcance mínimo y manejo específico por entorno.',
    vocabulary: {},
  },
  {
    id: 'q155',
    topicId: 'mcp-integration',
    prompt: 'The client connects to an MCP server and discovers a tool, but invocation returns an authorization failure. Which layer is MOST likely at fault?',
    options: [
      'File-name discovery only.',
      'Credentials, permissions, or authorization scope for the operation.',
      'The existence of the tool description.',
      'The model context window size.',
    ],
    answer: 1,
    explanationEs: 'Si hay conexión y discovery, pero falla la invocación por autorización, deben revisarse credenciales y permisos de esa operación.',
    vocabulary: {},
  },

  {
    id: 'q156',
    topicId: 'mcp-descriptions',
    prompt: 'Which MCP tool description BEST distinguishes search_users from get_user?',
    options: [
      'search_users: useful for users.',
      'search_users: search by name, email, or organization and return up to 50 summaries; use get_user when an exact user ID is known.',
      'search_users: powerful user tool.',
      'search_users: performs many operations.',
    ],
    answer: 1,
    explanationEs: 'La descripción correcta explica inputs, resultado, límite y diferencia frente a una herramienta similar.',
    vocabulary: {},
  },
  {
    id: 'q157',
    topicId: 'mcp-descriptions',
    prompt: 'Why should a tool description mention that an operation modifies or deletes data?',
    options: [
      'To make the description longer.',
      'To expose the side effect so the model can choose the tool only when appropriate.',
      'To remove the need for permissions.',
      'To guarantee that no confirmation is ever required.',
    ],
    answer: 1,
    explanationEs: 'Los efectos secundarios son parte del contrato y afectan la decisión, el riesgo y posibles aprobaciones.',
    vocabulary: {},
  },
  {
    id: 'q158',
    topicId: 'mcp-descriptions',
    prompt: 'A tool schema defines a required account_id, but the description says the account ID is optional. What is the BEST assessment?',
    options: [
      'The contract is clear because descriptions override schemas.',
      'The description and schema are inconsistent and should be corrected.',
      'The model should invent an account ID.',
      'The field should remain ambiguous to preserve flexibility.',
    ],
    answer: 1,
    explanationEs: 'Descripción y JSON Schema deben ser coherentes. Contradicciones provocan inputs inválidos o selección errónea.',
    vocabulary: {},
  },
  {
    id: 'q159',
    topicId: 'mcp-descriptions',
    prompt: 'Which description problem MOST increases incorrect tool selection?',
    options: [
      'Clearly stating when not to use the tool.',
      'Explaining result limits.',
      'Using vague marketing language without purpose, inputs, or boundaries.',
      'Differentiating preview from apply operations.',
    ],
    answer: 2,
    explanationEs: 'El lenguaje vago no entrega criterios operativos para elegir entre herramientas.',
    vocabulary: {},
  },

  {
    id: 'q160',
    topicId: 'tool-choice',
    prompt: 'A workflow must always return data through one required extraction schema. When is forcing a tool MOST appropriate?',
    options: [
      'When the specific structured tool invocation is mandatory for the contract.',
      'Whenever any tool is available.',
      'When the model should decide whether a tool is necessary.',
      'To compensate for an unrelated tool description.',
    ],
    answer: 0,
    explanationEs: 'tool_choice obligatorio tiene sentido cuando el contrato exige esa invocación estructurada.',
    vocabulary: {},
  },
  {
    id: 'q161',
    topicId: 'tool-choice',
    prompt: 'A workflow must obtain an account_id from an email and then retrieve transactions using that ID. What is the correct execution order?',
    options: [
      'Run both calls in parallel with an unknown account_id.',
      'Retrieve transactions first, then search for the account.',
      'Find the account, validate the returned ID, then retrieve transactions.',
      'Force the transaction tool to invent the missing ID.',
    ],
    answer: 2,
    explanationEs: 'La segunda llamada depende del output de la primera, por lo que debe ejecutarse después y validar el identificador.',
    vocabulary: {},
  },
  {
    id: 'q162',
    topicId: 'tool-choice',
    prompt: 'Three tools independently retrieve weather, exchange rates, and news before a summary. What is the BEST plan?',
    options: [
      'Run them sequentially because all tool calls must be serial.',
      'Run them in parallel, then synthesize the results.',
      'Force only one tool and infer the other results.',
      'Generate the summary before invoking the tools.',
    ],
    answer: 1,
    explanationEs: 'Las llamadas no dependen entre sí y pueden ejecutarse en paralelo; la síntesis espera sus resultados.',
    vocabulary: {},
  },
  {
    id: 'q163',
    topicId: 'tool-choice',
    prompt: 'When should a system generally avoid forcing a specific tool?',
    options: [
      'When policy requires one mandatory validation.',
      'When the output must follow one required schema.',
      'When several tools may be appropriate depending on evidence not yet known.',
      'When an authorized user explicitly requests one supported action.',
    ],
    answer: 2,
    explanationEs: 'Cuando la herramienta correcta depende de evidencia futura, forzar una opción elimina flexibilidad y puede provocar una invocación incorrecta.',
    vocabulary: {},
  },
]
